### ISSUE TITLE
Provide example/documentation for side_effect

### ISSUE THREAD

**Issue by zstyblik** [ansible-community/molecule#1599]
# Issue Type

- Feature request

# Molecule and Ansible details

Not applicable

# Desired Behavior

Hello,

please, would it be possible to provide more documentation/examples of what side_effect is and how to use it. I know the feature exists, but I haven't really found any documentation on what it is, what good is it for or how to use it.

Thanks

**Comment by lwm** [comment]
From https://molecule.readthedocs.io/en/latest/configuration.html#provisioner:

> The side effect playbook executes actions which produce side effects to the instances(s). Intended to test HA failover scenarios or the like. It is not enabled by default. Add the following to the provisioner’s playbooks section to enable.
> 
> provisioner:
>   name: ansible
>   playbooks:
>     side_effect: side_effect.yml
> 
> Important
> 
> This feature should be considered experimental.
>

**Comment by lwm** [comment]
Probably worth to add a note to https://etherpad.openstack.org/p/ansible-molecule which is a brain dump for how we can improve the documentation right now. This is definitely not easy to find and we should change that.

**Comment by zstyblik** [comment]
@lwm, I appreciate your reply. I've read documentation. I even tried to dig into provisioner related code.

I'm "begging", for the lack of better word, for some example of "do this, do that, voilà you get banana". What kind of "code" should go inside `side_effect.yml`? Any real world example? Surely, somebody had to use it at least once.

I mean no offense. If no such thing is possible eg. it's experimental and we don't know yet, then it's not possible. I'm cool with that.

**Comment by lwm** [comment]
> I mean no offense. If no such thing is possible eg. it's experimental and we don't know yet, then it's not possible. I'm cool with that.

All good! No problems. I think it's being done by someone but nothing in the tests (well, I did [a quick check](https://github.com/ansible/molecule/search?q=side-effect&unscoped_q=side-effect)). I don't have anything further :/ I've added a note to the etherpad and hopefully we can get something for this. If you do any experimentation (or anyone!) please let us know in this issue.

**Comment by mechastorm** [comment]
Until official docs are included, I found the usage of `side_effects` after some experimentation

Include path to the `side_effect.yml` as documented in https://molecule.readthedocs.io/en/latest/configuration.html#provisioner and mentioned by @lwm 

```yml
provisioner:
  name: ansible
    side_effect: side_effect.yml
```

Then create the file `side_effect.yml` in your scenario folder (ie. `molecule/default/side_effect.yml`)

```
---
- name: Side Effect
  hosts: all
  become: true

  tasks:
    - include_vars:
        file: ../../defaults/main.yml

    - include_vars:
        file: ../default/_inputs/test_vars.yml

    - name: [EXAMPLE] Start the services
      service:
        name: myservice
        state: started
```

To run it, you can run the command `molecule side-effect`

The `side-effect` is already included in the `converge` step as documented here https://molecule.readthedocs.io/en/latest/configuration.html#scenario
