### ISSUE TITLE
Including certificates in molecule.yml via environment variable

### ISSUE THREAD

**Issue by nkabir** [ansible-community/molecule#1622]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible 2.7.4
  config file = None
  configured module search path = ['/home/nkabir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nkabir/.local/opt/xcatalyst/venvs/xpack-python-xpack/lib/python3.6/site-packages/ansible
  executable location = /home/nkabir/.local/opt/xcatalyst/venvs/xpack-python-xpack/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
molecule, version 2.19.0

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

Defined a certificate in environment:

```
$ echo "$LXD_LOCAL_CERT"
-----BEGIN CERTIFICATE-----
MIIFQzCCAyugAwIBAgIQL7+KILnzKjWeZ9/8ZGFUEzANBgkqhkiG9w0BAQsFADA1
MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGgt
bHBjLTAwHhcNMTgxMDI2MDEwNzM5WhcNMjgxMDIzMDEwNzM5WjA1MRwwGgYDVQQK
ExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGgtbHBjLTAwggIi
MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDqjMztY0kvZY6NVTRqzicJVZu
Ty0wa/++gSDhTGijn6jljFrWciNk8j3mouxNzQ/nEIYIsl+GWoZANPF7V1IA56Zu
TxAnqoY0UYK91UGNIylk/bXYhg2ulnnxiwLnL8TXz6FkHJ0V3boPTTceXTPy8gFA
FgCiyZRWMgxY5PIuECZ0sF3aUTpz3clgQV31wE/40pD7QJKSrKYMO+DFKL+zmTTd
LtslnlHBD8W3IkdHp3nIKmMfMFgGV9l4pR285b2uFqkxiYPIDDYNIvYBJr2W2IPG
P3Ax7SlGL52Djl9GBLRXTPLDr42axZyWO0T0be3DEeCF/8t9xInCmzXSy2XHzUsy
VHtWHi2QRZwKNH5pcm+l7pP8X44LbIks/dkIGQ/dATN8T/Kt2WcAJiISRlanmGr/
lgk0Y7bhDCgwRAOmxtr2HNaeDezFCreNTmrm14w8g18k7wD4836ciUJfHBcci5TA
d2i5ie2pNi64DjpM34FQFVn+gDL17am1lOpgEvw97NZhE0TT5ZSORjUt43jE6g0+
w/gY0i4tPGlAno0+35r1MnRayh84QPKnyPg/NUlwaTWj/QEzAo1sy02ysYOubvJX
A5bc5OwZCukxX0pPMnEpCL2qtGpPk8gTCqnA4bJ6ykeJdtxM1x4f7jm42FFyBzmj
T96eO6cvd8J4A7D4NwIDAQABo08wTTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAYBgNVHREEETAPggdoLWxwYy0whwQK
AchkMA0GCSqGSIb3DQEBCwUAA4ICAQCpCA59OnCt/tOCA4bwMUNCxIC0Mb69UNhM
qKtkIML4oebq28p7WrElx89vdd9VYFJMhrk85/wN7oJdRTs1lVIg4UYxS5mFFoCr
NrGiQTY6NHrScOhlTFx52CKQ0XIdMVQO4LzIwadGVJn/iplhsTxFQgUoe16dn1MO
KMizmeQslJ1z7zVA/okmPl0qO5GvTlrHdavA/qXuaktEukENvs+M1SCwlxTRpQzv
WJYkSSabxSNov+gvltbMuJASRpL44E1Nsycn/X2W0ImeXK4GPlOZJuEtwSATxlgS
g5ppbnt71ww/W7tHG4EKdVI8jz/XiiYZWfmJYe5Gew1pVdicqo3GI11ZFcKHGKFi
o7AdbcuIcD/f9jrAY6DxDypBfIk6schLZBSY8JimfQZ5VX6eDlZMkXrvOrQjX1PZ
mMzb7BOi1hXtpTIwIkxIIIx0mTRo/mw3Nu88YMbPQPUc15wf9GpA6NtV4fWyHX7p
lF7fqP1BN6paT2aD/JeP0+YJLH2x0WkCPQfAPZRx0UkNm6COR8B1tfUiFZCQA8/g
r4LcxbeTJn8BZOxopkHGOuH+ZJ4eQR39Ga9kuEVNHPR10BrU5oUKRH7r65SEFUJQ
fMLeoiVPA874GwwxmlKaj7gyF431TT/qiNbXlj19Y0cOcoyKmphIBVrwyAXGse9c
1FsluXBWug==
-----END CERTIFICATE-----
```

to access in `molecule.yaml`

```
---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: instance
    url: https://localhost:8443
    trust_password: secret
    source:
      type: image
      mode: pull
      server: https://localhost:8443
      # Generate server certificate with 'lxc remote add localhost'
      # add server certificate here
      certificate: |
        ${LXD_LOCAL_CERT}
      protocol: lxd
      alias: bionic-stock
    architecture: x86_64
    profiles:
      - default
    force_stop: false
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

# Actual Behaviour
Parsing fails for multiple-line values (works fine for a single line):

```
$ molecule --debug test
ERROR: while scanning a simple key
  in "<unicode string>", line 23, column 1:
    MIIFQzCCAyugAwIBAgIQL7+KILnzKjWe ... 
    ^
could not find expected ':'
  in "<unicode string>", line 24, column 1:
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5l ... 
    ^
```
