### ISSUE TITLE
YAML lint config (.yamllint) is overwritten after `molecule init`

### ISSUE THREAD

**Issue by rockpenguin** [ansible-community/molecule#1631]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.5
  config file = ~/dev/ansible/ansible-control/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/dev/ansible/ansible-control/.venv/lib/python3.7/site-packages/ansible
  executable location = ~/dev/ansible/ansible-control/.venv/bin/ansible
  python version = 3.7.1 (default, Nov  6 2018, 18:49:54) [Clang 9.0.0 (clang-900.0.39.2)]
molecule, version 2.19.0
```

Molecule installation method: pip

Ansible installation method (one of): OS package (Homebrew)

# Desired Behaviour
My `.yamllint` should remain intact, and not be overwritten :-)

# Actual Behaviour

1. Create or make changes to .yamllint, e.g.

```
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
```
2. Run `molecule init scenario --role-name <role-name> --scenario-name <run-this>`
3. Open `.yamllint` in fav editor, and it's back to the default from molecule:

```
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
  # NOTE(retr0h): Templates no longer fail this lint rule.
  #               Uncomment if running old Molecule templates.
  # truthy: disable
```
Thanks!
