### ISSUE TITLE
Using --base-config on Molecule 2.17.0+ breaks at Destroy sequence (but works in debug mode)

### ISSUE THREAD

**Issue by Rickkwa** [ansible-community/molecule#1661]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```
```
ansible 2.7.5
  config file = None
  configured module search path = ['/home/travis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ansible
  executable location = /home/travis/virtualenv/python3.6.3/bin/ansible
  python version = 3.6.3 (default, Nov 28 2017, 18:47:21) [GCC 4.8.4]
molecule, version 2.19.0
```

(also applies to Molecule 2.18.0, and 2.17.0)

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

- Ran in Travis CI

# Desired Behavior

I split a `molecule.yml` to extract common configuration into a base config with the intention of using it for multiple scenarios.

```yaml
# molecule-base.yml
---
scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
driver:
  name: docker
lint:
  name: yamllint
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
```

```yaml
# molecule.yml
---
scenario:
  name: default
platforms:
  - name: instance
    image: centos:7
```

After running `molecule --base-config ./molecule-base.yml test` on a minimal project with a default molecule scenario aside from the above configuration, I expect the tests to pass.

# Actual Behaviour

The run fails on the Destroy sequence at the "Destroy molecule instance(s)" task. I tried running the command in debug mode so that I can see what exactly failed in the playbook. But interestingly enough, the command succeeds when ran with `--debug`.

I have provided a minimal example here:
* Code: https://github.com/Rickkwa/molecule-test/tree/9fc93646b9429eb29fcbc8f89b73903f16c6f7fa
* Travis Build: https://travis-ci.com/Rickkwa/molecule-test/builds/97139188

In the Travis build, I ran the same command using 4 versions of Molecule (`2.19.0`, `2.18.0`, `2.17.0`, `2.16.0`). For each version, I run it both with debug on and off. This bug happens in all versions except `2.16.0`.
