### ISSUE TITLE
[investigate]: use of molecule with multi-role repositories

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#1744]
This tricket should be used for documenting current challanges that we may face for enabling molecule use in multi-role repositories.

1. MOLECULE_GLOB could be make user-overridable for allowing molecule to look inside each role directory.
2. Duplicate scenario names in different folders should be allowed: `ERROR: Duplicate scenario name 'default' found.  Exiting.` -- clearly we could have "default" on each role.
3. use should be able run molecule from any subdir of a git project, just like tox.
4. molecule should auto-load its base-config from the root of the current (git) project (look up cwd for first .git dir)
5. user should be limit molecule run on a single role, like `molecule -r foo list`
6. role and scenario filters should be supported as options instead of command args because they would make sense for most commands. Running `molecule --help` shoudl list them, without needing to ask user to do a `molecule [list|lint|matrix|test|....] --help` in order to see that they add `-s foo` argument. Yep, for very few commands these do not make sense, but they can just be ignored in those cases (if we **really** want we can even add argparse logic to disalow that).

To track progress on implementing the multi-role testing with molecule we should create an empty project for testing this use.

**Comment by lwm** [comment]
Hey @ssbarnea, could you explain further point number 6? I didn't quite grok it. 

The other points seem reasonable and useful! Thanks for pushing this forward.

**Comment by ssbarnea** [comment]
@lwm Sure, let me try to  describe it here and later we can rephrase the ticket to make it clear.

Expected behaviour:
```
molecule --help
# output should include a line like:
-s, --scenario SCENARIO       Limit molecule execution to SCENARIO
```
Currently this information is displayed only when you run `molecule list --help` (or other command),

15/16 currently listed commands to allow -s param, only one does not. It would be better to document these shared arguments at the root-level instead of displaying them only when a command is added.

True that we need to be careful not to make then disapear from the current location when doing that.

**Comment by lwm** [comment]
@ssbarnea, thanks for that. I am not sure agree that this would be better. However, I'd rather not block your progress and motivation on this multiple role functionality. This discussion on CLI parameter discovery seems out of scope for the minimal steps needed at making Molecule better at handling multiple roles, so maybe we can leave it out for now? I think we need to improve the CLI in general and this discussion will be part of that.

**Comment by Lirt** [comment]
Hi,

To add my ideas to point 4.

When working with monorepos, it would be nice to have a way to split `molecule.yml` into multiple parts, where there would be one common part (root), which will be read as first, and other role specific parts with overrides (or decorations) for the common root part.

So the common `molecule-common/molecule.yml` configuration in my example is:

```yaml
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: molecule-test-0
    zone: europe-west1-b
    machine_type: n1-standard-1
    image_family: ubuntu-1604-lts
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
verifier:
  name: inspec
```

Then role specific `roles/my-role/molecule/default/molecule.yml` with decorations and overrides could look like:

```yml
platforms:
  - name: molecule-my-role-0
    zone: europe-west1-b
    machine_type: n1-highcpu-2
    image_family: ubuntu-1604-lts
provisioner:
  playbooks:
    destroy: destroy-and-cleanup.yml
```

Then if this was done internally by molecule, it would be great, but I think there are also different possibilities, like including/importing some common configurations from different files (Currently not implemented).

Question is maybe also if the yaml dicts and lists are merged or overwritten.
