### ISSUE TITLE
[docker_network] Allow more options

### ISSUE THREAD

**Issue by rockandska** [ansible-community/molecule#1879]
# Issue Type

- Feature request

# Desired Behavior

For now it seems impossible to use `docker_network` options other than `name` ([create.yml#L51-L56](https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml#L51-L56))

Would be handy to have the other options available.

For example, i want to test the availability of a VIP (deployed with haproxy / keepalived roles) and I need to be sure that the VIP i test will not be taken by a container, so to avoid this, i fix the network/ip range used by the network dedicated to the tests.
The only workaround i've found for now is to update the network in "prepare.yml" and restart the attached containers but will be better to have all configuration in one place :)

```
- name: Update docker network
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: "Update docker network: my_docker_network"
      docker_network:
        name: "{{ item }}"
        docker_host: "{{ item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        ipam_options:
          subnet: 172.28.0.0/16
          iprange: 172.28.5.0/24
          gateway: 172.28.5.254
        force: true
      with_items: "{{ molecule_yml.platforms | molecule_get_docker_networks | unique }}"
      when: item == 'my_docker_network'

    - name: "Restart containers"
      docker_container:
        name: "{{ item.name }}"
        docker_host: "{{ item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        state: started
        restart: true
        networks:
          - name: my_docker_network
        purge_networks: false
      with_items: "{{ molecule_yml.platforms }}"
```

Regards,
