### ISSUE TITLE
I though that ansible_ssh_user was deprecated ?

### ISSUE THREAD

**Issue by mehdicopter** [ansible-community/molecule#2240]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.8.4

molecule --version
molecule, version 2.22
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I would like to use one scenario for AWS but using multiple platforms.
But even by supplying `ansible_user`, it is using the `ssh_user` from `create.yml` which is `ubuntu`.

# Actual Behaviour

My actual config:
```
---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: ec2-centos6
    image: ami-07fa74e425f2abf29
    instance_type: t2.micro
    vpc_subnet_id: subnet-d25fb0b8
    groups:
      - centos
  - name: ec2-centos7
    image: ami-04cf43aca3e6f3de3
    instance_type: t2.micro
    vpc_subnet_id: subnet-d25fb0b8
    groups:
      - centos
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  inventory:
    group_vars:
      centos:
        ansible_user: centos
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
```
Now when I run this:
```
molecule --debug converge --scenario-name aws
[...]
TASK [Gathering Facts] *********************************************************
    task path: /Users/mmahfoudi/Github.mehdicopter/ansible-role-epel/molecule/aws/playbook.yml:2
    <18.194.219.241> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    <18.194.219.241> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/Users/mmahfoudi/.cache/molecule/ansible-role-epel/aws/ssh_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o ControlPath=/Users/mmahfoudi/.ansible/cp/%h-%p-%r x.x.x.x '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
    <x.x.x.x> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    <x.x.x.x> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/Users/mmahfoudi/.cache/molecule/ansible-role-epel/aws/ssh_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o ControlPath=/Users/mmahfoudi/.ansible/cp/%h-%p-%r x.x.x.x '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
    <x.x.x.x> (255, '', "Warning: Permanently added 'X.X.X.X' (RSA) to the list of known hosts.\r\nubuntu@x.x.x.x: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n")
    <x.x.x.x> (255, '', "Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.\r\nubuntu@x.x.x.x: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n")
    fatal: [ec2-centos6]: UNREACHABLE! => {
        "changed": false,
        "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'x.x.x.x' (RSA) to the list of known hosts.\r\nubuntu@x.x.x.x: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
        "unreachable": true
    }
    fatal: [ec2-centos7]: UNREACHABLE! => {
        "changed": false,
        "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.\r\nubuntu@x.x.x.x: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
        "unreachable": true
    }

    PLAY RECAP *********************************************************************
    ec2-centos6                : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
    ec2-centos7                : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

ERROR:
```

**Comment by mehdicopter** [comment]
I know that if I change `ansible_user` to `ansible_ssh_user`, it works.
Modified config:
```
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  inventory:
    group_vars:
      centos:
        ansible_ssh_user: centos
        # ansible_user: centos
  lint:
    name: ansible-lint
```
But then I have a new
