### ISSUE TITLE
Add `molecule init collection`

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#2380]
# Issue Type
- Feature request
---

After #2342 we should move on to allowing ansible-galaxy to init collections for us. We have https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-molecule already. It's just a case of having ansible-galaxy do the work and then putting a molecule folder in.

Related to #2165.

**Comment by darmach** [comment]
I have some issues using molecule to test the module in a collection. Followed @geerlingguy article linked above, however molecule does not seem to pick up the module for me:
```
--> Action: 'converge'
--> Sanity checks: 'docker'
ERROR! couldn't resolve module/action 'my_test'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/darmach/venvs/mytestrole2/mynamespace/mycollection/molecule/default/playbook.yml': line 16, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: Test the my_test module.
    ^ here

ERROR:
(mytestrole2 venv)[darmach@mbp] ~/venvs/mytestrole2/mynamespace/mycollection [4] $ tree
.
├── README.md
├── docs
├── galaxy.yml
├── molecule
│   └── default
│       ├── INSTALL.rst
│       ├── molecule.yml
│       ├── playbook.yml
│       └── tests
│           ├── __pycache__
│           │   ├── test_default.cpython-37-pytest-5.2.2.pyc
│           │   └── test_default.cpython-37.pyc
│           └── test_default.py
├── plugins
│   ├── README.md
│   └── modules
│       └── my_test.py
└── roles

8 directories, 10 files
```

Used following ansible and molecule versions:
```
pip install git+https://github.com/ansible/ansible.git@devel
pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple molecule==3.0a4.dev41
```
Are these correct? Am I doing something wrong?

**Comment by decentral1se** [comment]
@darmach please do not spam our issues (you posted the same on the other ticket). Use StackOverflow, the mailing list, the IRC. This is for tracking a feature for the project, not a support space. I'm marking your comment as off-topic.

**Comment by decentral1se** [comment]
We can move ahead with https://github.com/ansible/molecule/pull/2342.

**Comment by tadeboro** [comment]
I am not sure if the `molecule` folder should live in the root of the Ansible collection. Upstream's recommendation is to place tests into the `tests` folder. More info can be found [here](https://www.ansible.com/quality-matters) (I know it is a bit sad that the only real testing-related documentation is session recording from AnsibleFest, but better this than nothing).

For example, in [sensu.sensu_go collection](https://github.com/sensu/sensu-go-ansible), we placed molecule tests under `tests/integration`, because this is what molecule tests are at their core.

**Comment by decentral1se** [comment]
It's unclear where Ansible core are going and I'd rather not step on their toes. When there is a consensus for this tests folder convention from core then I would consider it.

**Comment by greg-hellings** [comment]
Personally I've taken to dropping the molecule tests inside of the individual roles that they are testing for. Is there a reason to not continue doing that?

**Comment by geerlingguy** [comment]
@greg-hellings - A number of collections don't have any roles... and some collections only have roles. Others are a mix of roles and modules (and someday possibly other things like playbooks too).

I find value in being able to use molecule with all three of these primary resources.

**Comment by ssbarnea** [comment]
Cleary this is something we do want to do. A PR is more than welcomed here. Ideally we should generate something that has a little bit of each mentioned parts, making easy for users to build on top of it, or to remove stuff they do not need. 

If you have such an example repo, I can help converting it to a cookiecutter template.

**Comment by greg-hellings** [comment]
@geerlingguy I get that. I haven't yet had a need for a collection that's modules only but it's a very understandable workflow.

For all my roles I've taken to using tox inside of my collection to isolate testing. I even wrote a [plugin for tox](https://github.com/greg-hellings/tox-ansible) to help. It automatically generates a tox environment and sets an appropriate "molecule test -s foo" to run every scenario in its own configured environment. It also lets me filter and only run scenarios based on a single role (--ansible-role foo), a single scenario name (--ansible-scenario bar) or a single scenario driver (--ansible-driver openstack). This is currently at use within my two personal collections and our first collection coming out of RHQE's CI efforts.

I wonder if a similar type of thing, or even an enhancement to it, can help isolate molecule tests running elsewhere within a collection's space to test other components. Then a skeleton could be used to quickly configure appropriate tox options?

**Comment by Yajo** [comment]
IMHO molecule should support building and installing a local collection from a directory.

What I do right now is:

```yaml
# molecule.yml
depencency:
  name: shell
  command: ansible-playbook molecule/default/dependency.yml
# ...


---
# dependency.yml
- name: install dependencies
  hosts: localhost
  tasks:
    - name: build tested collection
      command:
        argv:
          - ansible-galaxy
          - collection
          - build
          - --force
          - --output-path={{ playbook_dir }}/collections
          - "{{ playbook_dir }}/../.."

    - name: install tested collection
      command:
        argv:
          - ansible-galaxy
          - collection
          - install
          - --force
          - --collections-path={{ playbook_dir }}/collections
          - "{{ playbook_dir }}/collections/mynamespace-mycollection-{{ (lookup('file',
            '../../galaxy.yml')|from_yaml).version }}.tar.gz"
```

This way I instruct molecule to build and install the collection it is testing locally. However this feels kind of hacky; IMHO I should be able to just do this:

```yaml
# molecule.yml
dependency:
  name: galaxy
# ...

---
# requirements.yaml
collections:
  - name: mynamespace.mycollection
    src: ../..
---

Although I gess this is more ansible galaxy's problem than molecule, right?
