### ISSUE TITLE
Very hard to find reason for `Create molecule instance(s)` or `Wait for instance(s) creation to complete` tasks fail.

### ISSUE THREAD

**Issue by jonpugh** [ansible-community/molecule#2450]
# Issue Type

- Feature request

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.9.1
  config file = None
  configured module search path = ['/home/jon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jon/Projects/devshop/python/lib/python3.7/site-packages/ansible
  executable location = /home/jon/Projects/devshop/python/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
molecule, version 2.22
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# molecule.yml

I am setting up molecule for my roles just like @geerlingguy. 

My mistake was in the default environment name: I used "ubuntu18" instead of "ubuntu1804". It took me hours and hours to realize that was the problem.

```
platforms:
  - name: instance-${MOLECULE_DISTRO:-ubuntu18}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu18}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
```

# Desired Behavior

When I make the simple mistake of entering a bad docker image name, `molecule test` will fail on the task `[Wait for instance(s) creation to complete]`, but with no indication of why it failed beyond this error message:

```
'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'
```

After digging around for quite some time, I ended up using `molecule --debug`, which didn't give me the answer, but did provide a clue:

 ```
    TASK [Create molecule instance(s)] *********************************************
 changed: [localhost] => (item=instance-ubuntu18) => changed=true 
      ansible_job_id: '373705094385.150922'
      ansible_loop_var: item
      finished: 0
      item:
        command: sleep infinity
        hostname: devshop.local.computer
        image: geerlingguy/docker-ubuntu18-ansible
        name: instance-ubuntu18
        pre_build_image: true
        privileged: true
        volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      results_file: /home/jon/.ansible_async/373705094385.150922
      started: 1
```

I decided I should probably look into the "results_file":
```
$ cat /home/jon/.ansible_async/373705094385.150922
{"msg": "Error pulling image geerlingguy/docker-ubuntu18-ansible:latest - 404 Client Error: Not Found (\"pull access denied for geerlingguy/docker-ubuntu18-ansible, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\")", "failed": true, "exception": "  File  ....
```

Ah ha!

Wrong image name.  :man_facepalming: 

Would be great if this error message was surfaced all the way up to `molecule test` commands without `--debug`.

Thanks for the great tool!
