### ISSUE TITLE
Merge problems between base-config and molecule.yml. Causing create.yml ERRORS

### ISSUE THREAD

**Issue by gabyfulchic** [ansible-community/molecule#2477]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.10
molecule 2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior
I would like my base-config to merge with molecule.yml correctly. Actually the params `dockerfile`   and `image` from base-config.yml are ignored and skipped in the "Create Dockerfiles from image    names" task. I would like the `molecule_yml.platforms` object to be merged between base-config.yml and molecule.yml at this step. 

# Actual Behaviour

So, currently, my use case is that i have this **base-config.yml** : 
```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../../.yamllint
platforms:
  - image: jrei/systemd-debian:9
    dockerfile: ../../../../test/molecule/Dockerfile.j2
    command: /lib/systemd/systemd
    env:
      container: docker
  - image: jrei/systemd-centos:7
    dockerfile: ../../../../test/molecule/Dockerfile.j2
    command: /lib/systemd/systemd
    env:
      container: docker
provisioner:
  name: ansible
  playbooks:
    create: ../../../../test/molecule/create.yml
    destroy: ../../../../test/molecule/destroy.yml
    converge: ../shared_files/converge.yml
  inventory:
    links:
      host_vars: ../../../../inventories/molecule/host_vars
  lint:
    name: ansible-lint
scenario:
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../shared_files/tests
  options:
    vvv: true
  lint:
    name: flake8
```

I set my **molecule.yml** as following : 
```
---
platforms:
  - name: molecule-bash-deb
  - name: molecule-bash-rhel
provisioner:
  log: true
scenario:
  name: default
```

I faced this error using `molecule -c ../../test/molecule/base-config.yml test` : 
![image](https://user-images.githubusercontent.com/22600727/71363032-17a27180-2598-11ea-875a-1d6bb69acf8c.png)
  

And as you can see here, i added some debug : 
![image](https://user-images.githubusercontent.com/22600727/71363066-30128c00-2598-11ea-8108-0d8129b8a570.png)

I added a task in the create.yml playbook to check the content of `{{ molecule_yml.platforms }}`. And I can see that there are only `molecule.yml` variables 🧐  
When i decide to fill `image` parameter in my molecule.yml, it gives me the same error but with `dockerfile` parameter. And when i decide to fill `dockerfile` param in my molecule.yml, all works good and the variables used well came from my base-config.yml.   
  
That's why I'm sure that the problem is only from here : 
![image](https://user-images.githubusercontent.com/22600727/71363227-c5158500-2598-11ea-8eee-0f2ab263b086.png)
   
  
**I'm currently investigating to make a PR by myself but if you can drive me it would be good ! **
  
And **PS** yes i saw that PR passed : https://github.com/ansible/molecule/pull/2287/files.
So I tried with `molecule 2.22` & `molecule 3.0a4` and it's not works too for `image` and `dockerfile` params in the "Create Dockerfile from image names" step. (from `create.yml`)
