### ISSUE TITLE
Doc Bug: gitlab-ci config descriptive text incorrect

### ISSUE THREAD

**Issue by mancdaz** [ansible-community/molecule#2493]
# Issue Type
This is a doc bug regarding gitlab-ci config

# Bug report
PR https://github.com/ansible/molecule/pull/2112 edited the gitlab-ci config to remove tags and make it more generic. It also removed the part of the config where the virtualenv is setup. However, the descriptive text in the docs still contains:

```Here is an example setting up a virtualenv and testing an Ansible role via Molecule. User-level pip is cached and so is the virtual environment to save time. And this is run over a runner tagged pip36 and docker, because its a minimal CentOS 7 VM installed with pip36 from IUS repository and docker.```

# Desired Behavior

This is confusing given that the example config no longer uses tags or venv. I would suggest adding a separate config for users who want to use tags, and a more generic one for those who don't. I actually think the example using a venv is valuable and should be added back.
Either this, or the descriptive text needs to change to reflect what is actually in the current example.

# Actual Behaviour

See above description of doc bug

**Comment by ssbarnea** [comment]
@mancdaz Please make a PR that fixed this. I am not using GitLab CI and I am inclined to remove the docs intead of fixing it, unless someone proposes a fix.

**Comment by mancdaz** [comment]
@ssbarnea ok no problem - I think it's a very useful example to have so please don't remove it - I will make a PR to fix the docs.

**Comment by belfast77** [comment]
@mancdaz I'd like to test it soon as your ready if that is OK? Are you planning on sticking with Centos 7 in your example or moving to 8 ?

**Comment by mancdaz** [comment]
@belfast77 I will try and get to it as soon as I can. It will take a little time as I need to ensure the example `.gitlab-ci.yml` configs actually work!

I think for the example config, it doesn't really matter if the image being booted is cent7 or cent8 as it's not material to the actual example

**Comment by belfast77** [comment]
@mancdaz just getting Molecule to to install for the first time on centOS 7.7, that was painful for someone as new to it as I am. 
Trying to get virtualenv setup with Python 2.7 end of its life warnings for January 1st, 2020. 
Docker-compose won't install because it needs zipp
zipp won't install because it needs wheel, zipp and wheel won't install without setuptools
Then setuptools won't install because it needs to be pinned to `setuptools<45`
I was following the docs which say "Python 2.7 or Python >= 3.5 with Ansible >= 2.5"
Python 3 is not installed by default in CentOS 7
Anyway I learnt some some stuff along the way, so I'm good now.


I’ll try with a runner on Centos 8 as @ssbarnea suggested next and see how much easier that is.
However the main molecule Docs don't mention using Centos8 in the example.

Anyway this is my .gitlab-ci.yml so far (seems to currently be working but I'll need to do further testing.) I could of cousre be barking up the wrong tree.
```
---
stages:
  - test

# variables: Default Centos 7 uses git version 1.8.3.1 . This version doesn't support command "git fetch-pack: expected shallow list "
# Therefore using GIT_STRATEGY: clone
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"
  GIT_STRATEGY: clone

cache:
  paths:
    - .pip/
    - virtenv/

before_script:
  - pip install virtualenv
  - virtualenv virtenv
  - source virtenv/bin/activate

molecule:
  stage: test
  tags:
    - molecule-jobs
  script:
    - docker -v
    - python -V
    - pip install ansible molecule docker
    - ansible --version
    - molecule --version
    - molecule --debug test 
```
