### ISSUE TITLE
use ansible_host hostvar in inventory 

### ISSUE THREAD

**Issue by IlyesSemlali** [ansible-community/molecule#2552]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.8.6
  config file = None
  configured module search path = [u'/home/enedis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/enedis/.venv/hdr-indus/lib/python2.7/site-packages/ansible
  executable location = /home/enedis/.venv/hdr-indus/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]


molecule, version 2.22
```

Molecule installation method :  pip

Ansible installation method : pip

# Desired Behavior

When using the docker driver for instance, the generated inventory looks like this : 
```yaml
elastic:
  hosts:
    elastic_1-500c8346-ba3e-4aaa-b4b5-f1c383847e06:
      ansible_connection: docker
    elastic_2-500c8346-ba3e-4aaa-b4b5-f1c383847e06:
      ansible_connection: docker
    elastic_3-500c8346-ba3e-4aaa-b4b5-f1c383847e06:
      ansible_connection: docker
```
When using the --parallel option, the instance name bares an UUID which leads to errors when fetching hostvars based on this name. 
It could be easier to use parallelism with molecule if the inventory took advantage of the ansible_host variable like in the following inventory: 

```yaml
elastic:
  hosts:
    elastic_1:
      ansible_host: elastic_1-500c8346-ba3e-4aaa-b4b5-f1c383847e06:
      ansible_connection: docker
```
