### ISSUE TITLE
Validation of verifier's `env` option keys is too restrictive

### ISSUE THREAD

**Issue by ouroboros8** [ansible-community/molecule#2580]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.9.5
  ...
  python version = 3.8.1 (default, Dec 27 2019, 18:06:00) [Clang 11.0.0 (clang-1100.0.33.16)]
molecule 3.0.2
   ansible==2.9.5 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

- testinfra

# Desired Behavior

The `env` option on molecule verifiers allows users to pass environment variables with mixed- or lower-case names to the verifier.

# Actual Behaviour

[Current validation](https://github.com/ansible-community/molecule/blob/master/molecule/model/schema_v3.py#L225) does not allow lower-case letters in environment variable names.

To reproduce use the following molecule config:

```yaml
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
  env:
    foo: bar
```

And run molecule:

```
$ molecule --debug test
ERROR: Failed to validate.

{'verifier': [{'env': [{'foo': ["value does not match regex '^[A-Z0-9_-]+$'"]}]}]}
```
