### ISSUE TITLE
Proposal: Support Both entrypoint and command with Simplified Default

### ISSUE THREAD

**Issue by hswong3i** [ansible-community/molecule#2593]
# Proposal: Support Both `entrypoint` and `command` with Simplified Default

*Author*: Wong Hoi Sing Edison <@hswong3i>

*Date*: 2020-02-29

- Status: New
- Proposal type: core design, schema changes
- Estimated time to implement: **DONE** (see #2591)

## Motivation

For docker and podman driver, by default we only handle the `command` overwrite with `sleep infinity`.

### Problems

In case base image have both `ENTRYPOINT` and `CMD` specified, our `sleep infinity` may not functioning correctly.

## Solution proposal

- Add `entrypoint` for `ENTRYPOINT` support, with default `''`
  - `''` means enforce rollback to docker's build-in default `ENTRYPOINT` with `/bin/sh`
  - **NOT** setting it as `/bin/sh` else it will be replaced into `exec /bin/sh` which not works
  - See https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime#entrypoint-default-command-to-execute-at-runtime
- Update `command` with new default `bash -c "sleep infinity"`
- Remove `override_command` for simplify logic

For simple test case which we are NOT care about the base image original `ENTRYPOINT` and `CMD`, with this patch we will default it with `''` and `bash -c "sleep infinity"` therefore generally working for Molecule:

```
platforms:
  - name: instance
    image: centos:7
    entrypoint: ''
    command: 'bash -c "sleep infinity"'
```

In case we ARE caring about the base image origin `ENTRYPOINT` and `CMD` (e.g. [mariadb:10.4](https://github.com/docker-library/mariadb/blob/master/10.4/Dockerfile)), just simply set them as `~` in order to resume the original behavior:

```
platforms:
  - name: instance
    image: mariadb:10.4
    entrypoint: ~
    command: ~
```

When combine with systemd based container we could specify `ENTRYPOINT` and `CMD` as `init` and `bash -c "sleep infinity"`, therefore much similar as real world production use cases:

```
platforms:
  - name: instance
    image: centos:7
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    entrypoint: init
    command: 'bash -c "sleep infinity"'
    tty: True
    environment:
      container: docker
```

## Dependencies (optional)

N/A

## Testing (optional)

Corresponding test cases updated (see #2591; moreover, CI passed)

## Documentation (optional)

Corresponding documentation updated (see #2591)

## Anything else?

Ultimately, if we `docker commit` the result container as a static image with original base image's `ENTRYPOINT` and `CMD` during `verify.yml`, we could therefore push this brewed image hub.docker.com as an alternative of [ansible-bender](https://github.com/ansible-community/ansible-bender) project with standard Ansible supporting.

**Comment by ssbarnea** [comment]
One thing that I do not like is that in order to restore original container functionality user is forced to re-definethe command or entrypoint in molecule config. I do not like that behavior and I am inclined to prefer to respect what a container already had defined.

I do not mind defining our own implicit values if container does not have any defined.

AFAIK, there are two major use cases for container with molecule:
- emulating clean systems, where the container has no services supposed to be running by default. For those we do want to avoid docker stopping the container and thus we have the sleep approach.
- sideload-container that do run services and that are already supposed to be forever running due to this. In this case we probably can rely on them to remain-alive.

I am sure we cover well the first case, as this is how I use molecule currently in most places.

The second case is bit more nuanced and I can imagine a test scenario with 3 containers:

- centos-7 - used to test a mongodb client library running on centos-7
- centos-8 - used to test a mongodb client library running on centos-8
- mongodb - used to provide a mongodb server for the other two platforms

I do not expect the first two container images to be sleeping forever by their own but I do expect the mondogb to do so.

Can we make molecule working for both without forcing the user to add special configuration options to the molecule file?

**Comment by hswong3i** [comment]
@ssbarnea I found a simple workaround: simply rollback base image default with `~`, e.g.
```
platforms:
  - name: instance
    image: mariadb:10.4
    entrypoint: ~
    command: ~
```
