### ISSUE TITLE
Customizable docker image names created by molecule

### ISSUE THREAD

**Issue by domenicbove** [ansible-community/molecule#2616]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/dbove/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
molecule 3.0.2
```

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- source
- pip
- OS package

# Desired Behavior

Please give some details of the feature being requested

It would be nice to customize the names of the images created by molecule during `molecule create`

When molecule builds images based off dockerfiles, they all get created with the same name:
https://github.com/ansible-community/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml#L73

This can cause issues when you have something like this in your molecule.yml
```
platforms:
  - name: zookeeper1
    image: geerlingguy/docker-centos7-ansible
  - name: kafka_broker1
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile2.j2
```
