### ISSUE TITLE
Support Windows Docker containers

### ISSUE THREAD

**Issue by BlakeWills** [ansible-community/molecule#2648]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.9.6
  config file = None
  configured module search path = ['/home/blake/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/blake/.local/lib/python3.6/site-packages/ansible
  executable location = /home/blake/.local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
molecule 3.0.3
   ansible==2.9.6 python==3.6
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Firstly, apologies if this already works and I'm doing something wrong.

I'm trying to get Molecule to work with windows docker containers so I can test Ansible roles for windows.

I can get the create step working by overriding the command within the provider, as it was bash:
```
platforms:
  - name: instance
    image: ansiblewin:latest
    command: powershell.exe "while(1 -eq 1) { Start-Sleep -Seconds 10000 }"
    pre_build_image: true
```

However, I'm unable to get `converge` working because the docker driver defaults to using `sh` and there isn't a way to override it as far as I can see, resulting in the following error:

```
fatal: [instance]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. C
onsider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Un
restricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAkAHQAbQBwAF8AcABhAHQAaAAgAD0AIABbAFMAeQBzAHQAZQBt
AC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEUAeABwAGEAbgBkAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAcwAoACcAJQBUAEUATQBQACUAJwApAAoAJAB0AG0AcAAgAD0AIAB
OAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAdABtAHAAXwBwAGEAdABoACAALQBOAGEAbQBlACAAJwBhAG4AcwBpAGIAbABlAC0AdABtAHAALQ
AxADUAOAA2ADcAOAA5ADMAMAAwAC4ANgA4ADYANwA3ADgAMwAtADQANAA4ADAAMgA4ADgAMgA5ADQAMAA0ADgANwAnAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAd
AAgACQAdABtAHAALgBGAHUAbABsAE4AYQBtAGUACgBJAGYAIAAoAC0AbgBvAHQAIAAkAD8AKQAgAHsAIABJAGYAIAAoAEcAZQB0AC0AVgBhAHIAaQBhAGIAbABlACAATABBAFMAVABFAFgASQBUAEMATwBEAEUA
IAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAKQAgAHsAIABlAHgAaQB0ACAAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAH0AIABFAGwAcwBlACA
AewAgAGUAeABpAHQAIAAxACAAfQAgAH0A, exited with result 126, stdout output: container 5d136819d14b11a14b1eca78836000d3cc6edf05ca308c959466a68e0b386309 encountere
d an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)\n[Event Detail:  Provider:
 00000000-0000-0000-0000-000000000000]\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\n[Event Detail: onecore\\vm\\compute\\management\\orche
stration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF686C69D2B: (caller: 00007FF686C1E13A) Exception(8) tid(224) 80070002 The sys
tem cannot find the file specified.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \n Provider: 00000000-0000-0000-0000-0000000
00000] extra info: {\"CommandLine\":\"/bin/sh -c \\\"/bin/sh -c 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQ
BTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAkAHQAbQBwAF8AcABhAHQAaAAgAD0AIABbAFMAeQBzAHQAZQBtAC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AO
gA6AEUAeABwAGEAbgBkAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAcwAoACcAJQBUAEUATQBQACUAJwApAAoAJAB0AG0AcAAgAD0AIABOAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUA
IABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAdABtAHAAXwBwAGEAdABoACAALQBOAGEAbQBlACAAJwBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADUAOAA2ADcAOAA5ADMAMAAwAC4ANgA4ADY
ANwA3ADgAMwAtADQANAA4ADAAMgA4ADgAMgA5ADQAMAA0ADgANwAnAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdABtAHAALgBGAHUAbABsAE4AYQBtAG
UACgBJAGYAIAAoAC0AbgBvAHQAIAAkAD8AKQAgAHsAIABJAGYAIAAoAEcAZQB0AC0AVgBhAHIAaQBhAGIAbABlACAATABBAFMAVABFAFgASQBUAEMATwBEAEUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgA
FMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAKQAgAHsAIABlAHgAaQB0ACAAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAH0AIABFAGwAcwBlACAAewAgAGUAeABpAHQAIAAxACAAfQAgAH0A ; s
leep 0'\\\"\",\"WorkingDirectory\":\"/\",\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\n",
    "unreachable": true
}
```

Running `molecule --debug` shows that `docker exec` is calling `/bin/sh`, which obviously doesn't work in a Windows container:

```
EXEC ['/usr/bin/docker', '-H=tcp://localhost:2375', b'exec', b'-i', 'instance', '/bin/sh', '-c', "/bin/sh -c 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand ...
``` 

I've tried setting `ansible_shell_type` to Powershell, this still results in using `/bin/sh`:

```
provisioner:
  name: ansible
  connection_options:
    ansible_shell_type: powershell
```

It looks like running Molecule against windows containers isn't supported, hence raising this as a feature request.

**Comment by ssbarnea** [comment]
I am going to close this ticket because that is not a supported use-case and we do not have CI for testing it. 

Still, this does not mean that we will not accept a PR that is fixing the issue for you as long it does pass our CI. Yep, is still valid to open a PR against an already closed ticket.

**Comment by jimbo8098** [comment]
I was actually able to get a single Windows *VMs* (not containers) to spawn within a self-hosted Azure Pipelines agent runner buit it required a BIG workaround and effectively meant I could only test against a single Windows VM at a time.

Here's an example of my molecule environment:

https://gist.github.com/jimbo8098/25e29cbe0378e741d030fcb999cd7f8e

I wrote a wiki article for my organisation but there are big gotchas:

1. You can only run one VM at a time because you can only override connection_options once.
2. If running under Vagrant with Virtualbox on headless, set `provider_options.gui` to false otherwise you will experience issues with the provider.
3. The default prepare.yml file fails, you must diverge from it because it will use Linux-specific preperation. This is easily done by defining the prepare.yml as I've done in my gist. The prepare.yml contains:
```
---

- name: Prepare
  hosts: all
  tasks:
    
    - name: Do nothing
      debug:
        msg: "This is only here so we don't interrupt the prepare process on Windows"
```
This circumvents issues caused when you import an empty playbook (which molecule does). 

My solution for larger build testing was actually to do my tests through vagrant directly. This works fine most of the time but I don't benefit from all the advantages Molecule provides which is sad.

I seem to remember a PR to add Windows Docker container support somewhere but I can't track it down unfortunately. While the above isn't a specific fix for you, I suspect it might be helpful if you are spinning up just the one environment.

@ssbarnea is your feeling on this issue still the same? I opened an issue on molecule-vagrant to see if anyone had any answers too (https://github.com/ansible-community/molecule-vagrant/issues/98). I think it might be doable. Since that provider simply passes the commands through vagrant ssh, changing the ssh to winrm might be a simple fix for larger scale Windows tests. I'm aware Windows is problematic for CI testing but perhaps it's a step in the right direction.

**Comment by 1moere1** [comment]
@jimbo8098 you can by following this:

- Have a Windows host with Docker for Desktop installed and switched to Windows Containers
- Disable Windows Firewall on the Docker host.
- Prepare a Windows Container Image (winrm enabled, winrm setup to your needs like basic auth/AllowUnencrypted etc., user)
- Now setup your molecule.yml to something like this

```yaml
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: your_win10:20H2
    docker_host: 'tcp://<docker_host>:2375'
    command: "powershell 'while (1 -eq 1) {Start-Sleep -s 1000}'"
    exposed_ports: ["5985","5986"]
    published_ports: ["5985:5985","5986:5986"]
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: '<username>'
        ansible_password: '<password>'
        ansible_connection: winrm
        ansible_winrm_port: '5985'
        ansible_winrm_scheme: 'http'
        ansible_winrm_server_cert_validation: 'ignore'
        ansible_host: '<docker_host>'
verifier:
  name: inspec
```
