### ISSUE TITLE
Add MOLECULE_SUFFIX for naming uniqueness in molecule.yml

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#2670]
# Issue Type

- Feature request

# Molecule and Ansible details

Latest

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

My `molecule.yml` looks like so.

```yaml
---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: "myrolename-${INSTANCE_UUID}"
    server_type: cx11
    image: debian-10
provisioner:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint.yml .
  ansible-lint -c ../../.ansible-lint.yml
```

Where I export `INSTANCE_UUID` into the environment in order to have my VPS instance names not clash when different people are running builds that **should still be run in serial execution**. Therefore, `--parallel` is not an option here.

So, I think it would be nice to avoid this step and have some sort of "magic variable" exposed from molecule side so that I can use it as needed in the instance name through variable expansion.

If in agreement, I'll send a patch.
