### ISSUE TITLE
plugins: add role name to vars context for embedded converge.yml use case

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#2675]
# Desired Behavior

The default cookiecutter defined `converge.yml` is:

```
---
- name: Converge
  hosts: all
  tasks:
    - name: "Include {{ cookiecutter.role_name }}"
      include_role:
        name: "{{ cookiecutter.role_name }}"
```

Now, if you don't include a converge.yml in your molecule/default and your plugin provides a playbooks/converge.yml file then molecule will load that embedded playbook.

However, we can't embed that in a playbooks dir in the plugin packages because it will not know what the cookiecutter variable is when it is used. 

So, we need to inject the role name variable into the context here for this use case.

Seems simple to do.
