### ISSUE TITLE
Platform multi-word name causes instance failure

### ISSUE THREAD

**Issue by kevingentile** [ansible-community/molecule#2683]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible-playbook/library']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
molecule 3.0.3
   ansible==2.9.7 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

The platform name section supports a valid yaml string irrespective of underlying constraints

# Actual Behaviour

During the instance creation phase the `"sample instance"` name fails due to the space between words:
```
# molecule.yml
platforms:
  - name: "sample instance"
    image: <my_image>
    user: <my_user>
    hostname: <my_hostname>
    ...
```

Replacing the space with an underscore, the following modification will succeed in the instance creation section:
```
# molecule.yml
platforms:
  - name: "sample_instance"
    image: <my_image>
    user: <my_user>
    hostname: <my_hostname>
    ...
```
