### ISSUE TITLE
Ignore handlers (the Molecule way?)

### ISSUE THREAD

**Issue by AquaL1te** [ansible-community/molecule#2771]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 29 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
molecule 3.0.4
   ansible==2.9.10 python==3.8
```

Molecule installation method (one of):

- OS package: python3-molecule-3.0.4-1.fc32.noarch

Ansible installation method (one of):

- OS package: ansible-2.9.10-1.fc32.noarch

# Desired Behavior
When running tasks, a tag can be defined to either ignore it in Molecule as a test or for idempotency. But for handlers there is no such thing. I use at the moment `when: molecule_yml is not defined`. This is sufficient. But I wonder if there are better (builtin) ways. Because this when condition could also be used instead of using tags I guess. The reason I don't ignore the task that triggers the handler is because I want to test things as much as possible. So if the task itself can be tested, but only the handler needs to be skipped, then I prefer that. Just wondering if I can do this 'better'. I don't find information about ignoring handlers in the docs.

**Comment by alainchiasson** [comment]
Would you have a runnable sample repo to demonstrate your use case ? I think that would help the discussion.

**Comment by AquaL1te** [comment]
An example would be that the interfaces/IPs are not available in my Podman container I use to test my playbook. Creating an interface with e.g. the name 'eth0' and a certain IP like 192.168.1.1/24 is possible I guess? But I'm not sure if that's true for Podman. Therefore, I would like to run the tasks that setup the configuration files for e.g. Postfix, Apache, Dovecot, etc. But not restart the service or run any kind of handler that does any system check, such as e.g. `postmap`. Which would give an error about missing interfaces that are defined in the configuration.

So, as an example, a few handlers:
```
- name: postmap
  command: postmap /etc/postfix/{{ item }}
  loop:
    - canonical
    - relocated
    - virtual_alias
    - virtual_mailbox_domains
    - virtual_mailbox
  loop_control:
    label: "{{ item }}"
  when: molecule_yml is not defined

- name: postalias
  command: postalias /etc/aliases
  when: molecule_yml is not defined

- name: logrotate dovecot
  command: logrotate /etc/logrotate.d/dovecot
  when: molecule_yml is not defined

- name: restart dovecot
  service:
    name: dovecot
    state: restarted
    enabled: true
  when: molecule_yml is not defined
```

These are triggered by tasks, which I do want to run, because I want to check them for errors. But because there is a notify there, it will start it, or do some other action that will trigger an error when the handler is run at the end of the playbook. Tags inside handlers are ignored (as it seems, which makes sense since they're called via notify/listen). I don't want to ignore the tests for these tasks, since I do want to check for errors, but simply not start these services via notify/listen.

So my question is, is this the way someone should handle these kind of things? A runnable sample would be anything that notifies the above handlers. But maybe it would be an idea to investigate how far I can go with the creation of interfaces with Molecule + Podman. But compared to Docker, it seems [limited with Podman](https://molecule.readthedocs.io/en/latest/configuration.html#podman). If more info is needed then I'm happy to provide it.
