### ISSUE TITLE
Shell variable expansion

### ISSUE THREAD

**Issue by zyphermonkey** [ansible-community/molecule#2833]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.9.11
  config file = /home/vagrant/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python3.6/site-packages/ansible
  executable location = /home/vagrant/.local/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
molecule 3.0.6
   ansible==2.9.11 python==3.6

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

```sh
|
  set -e
  yamllint -f colored .
  ansible-lint --force-color
```

# Desired Behavior

Using shell expansion *+* fails inside of molecule.yml instead of correctly expanding/replacing

Trying to only include formatting characters if a variable is defined.  
```yaml
platforms:
  - name: instance${CI_JOB_ID:+-}${CI_JOB_ID}
```
According to the [docs](https://molecule.readthedocs.io/en/latest/configuration.html#variable-substitution) this should produce an instance name of either `instance` or `instance-<CI_JOB_ID>`.

[Further shell expansion information](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html):

> ${parameter:+word}
> parameter is null or unset, nothing is substituted, otherwise the expansion of word is substituted.

# Actual Behaviour

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](https://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

```yaml
ERROR: parsing config file '/ansible/roles/ca-sso-policyserver/molecule/default/molecule.yml'.

Invalid placeholder in string: line 11, col 19
---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -f colored .
  ansible-lint --force-color
platforms:
  - name: instance${CI_JOB_ID:+-}${CI_JOB_ID}
```
