### ISSUE TITLE
apt-get does not work on molecule ran via GitHub actions

### ISSUE THREAD

**Issue by aorfanos** [ansible-community/molecule#2892]
Same as #2116 

# Issue Type

- Bug report

# Molecule and Ansible details

```
Run ansible --version && molecule --version
ansible 2.10.2
  config file = /home/runner/work/ansible/ansible/ansible.cfg
  configured module search path = ['/home/runner/work/ansible/ansible/plugins/modules']
  ansible python module location = /opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/ansible
  executable location = /opt/hostedtoolcache/Python/3.8.1/x64/bin/ansible
  python version = 3.8.1 (default, Jun  9 2020, 20:20:25) [GCC 7.5.0]
molecule 3.1.2
   ansible==2.10.2 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Task should work:
```
- name: Fetch python3-apt package
  ansible.builtin.apt:
    name: python3-apt
    state: present
  update_cache: yes
```

Should be noted that I already install `python3-apt` in a previous action (where molecule, ansible and other dependencies are installed - this step executes successfully):

```
      - name: Install dependencies
        run: apt-get update && apt-get install python3-apt && pip3 install molecule docker yamllint ansible-lint
```
 
Also, my `molecule.yml` looks like this:

```
---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: "apache2"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: ansible
```
, and here's the whole CI job: https://pastebin.com/gVBrmBDp

# Actual Behaviour

```
    TASK [Install python3-apt] *****************************************************
Warning: 35m[WARNING]: Updating cache and auto-installing missing dependency: python3-apt
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not import python modules: apt, apt_pkg. Please install python3-apt package."}
```
