### ISSUE TITLE
No filter named 'molecule_header' or 'molecule_to_yaml' 

### ISSUE THREAD

**Issue by ekbfh** [ansible-community/molecule#2946]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible==2.9.14 , molecule==3.1.5
```

Molecule installation method (one of):
- pip3 

Ansible installation method (one of):

- pip3

# Desired Behavior

When i set up molecule 3.0.4 for example with ansible 2.9.14 it worked as it supposed, i have all filters.

# Actual Behaviour

```
    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
```

```
  TASK [Dump instance config] ****************************************************
    Monday 02 November 2020  13:09:51 +0000 (0:00:00.046)       0:00:28.665 *******
fatal: [localhost]: FAILED! => {}
MSG:
template error while templating string: no filter named 'molecule_header'. String: {{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}
```
