### ISSUE TITLE
Switch inventory for testinfra from inventory_file to inventory_directory

### ISSUE THREAD

**Issue by amarao** [ansible-community/molecule#2961]
# Issue Type
- Feature request

# Molecule and Ansible details
```
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/amarao/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/amarao/venvs/ansible29/lib/python3.8/site-packages/ansible
  executable location = /home/amarao/venvs/ansible29/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
molecule 3.2.0a0
    ansible:2.9.11 python:3.8
    delegated:3.2.0a0 from molecule
    libvirt:0.0.3 from molecule_libvirt
    openstack:0.1 from molecule_openstack
```

installation method
- pip

# Desired Behavior
Right now when testinfra is called, it's called with `self._config.provisioner.inventory_file`. This cause ansible-inventory (inside testinfra) to read inventory file. If inventory has links, `group_vars` and `host_vars` works fine, but `hosts` link is ignored. This creates a lot of problem with accessing variables from other hosts.

Consider this:
host_vars (or group_vars) for the instance:

```yaml
hypervisor: '{{ groups.hypervisor[0] }}'
hypervisor_ip: '{{ hostvars[hypervisor].ansible_host }}'
hypervisor_user: '{{ hostvars[hypervisor].ansible_user }}'
ansible_ssh_extra_args: '-J {{ hypervisor_user }}@{{ hypervisor_ip }}'
```
and this inventory:
```yaml
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ${TEST_BENCH_INVENTORY:-../../inventories/test_bench.yaml}
      group_vars: group_vars/
      host_vars: host_vars/
```
when converge playbook is called, it has access to other hosts inside `inventory_directory` (so I can uses `hostvars[hypervisor]`), but when testinfra is called, it can't see `hosts` link inside inventory directory, because right now testinfra is called with `self._config.provisioner.inventory_file`.

#Proposal

Change is to `self._config.provisioner.inventory_directory`.

# The problem
Right now testinfra is called without specifying hosts to test. If this change is made, testinfra would try to 'test' excessive hosts (like hypervisor in my case). This can be offset by passing explicit list of hosts to test (`--hosts` option) or by using special group for testing purposes.

My patch (which I used to verify the idea):

```
diff --git a/lib/molecule/driver/base.py b/lib/molecule/driver/base.py
index 5342c596..ff53e617 100644
--- a/lib/molecule/driver/base.py
+++ b/lib/molecule/driver/base.py
@@ -73,7 +73,7 @@ def testinfra_options(self):
         """
         return {
             "connection": "ansible",
-            "ansible-inventory": self._config.provisioner.inventory_file,
+            "ansible-inventory": self._config.provisioner.inventory_directory,
         }
```
