### ISSUE TITLE
ansible_args passed to all steps

### ISSUE THREAD

**Issue by t2d** [ansible-community/molecule#2963]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule 3.2.0a0
    ansible:2.9.7 python:3.8
    delegated:3.2.0a0 from molecule
    podman:0.3.0 from molecule_podman
    vagrant:0.5 from molecule_vagrant
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

I have a particular use case where I want to test a full playbook and it's roles. However, the playbook has to be called with specified tags. I would call the playbook in production like this:
```
ansible-playbook site.yml -t install
```
Therefore, I configured my `molecule.yml` like this:
```
---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: opensuse15
    box: generic/opensuse15
  - name: debian10
    box: generic/debian10
provisioner:
  name: ansible
  ansible_args:
   - --tags=install
  playbooks:
    converge: ../../site.yml
verifier:
  name: ansible
```
I would expect molecule to pass these parameters to the converge step only. 

# Actual Behaviour
Molecule passes the tags also to create and destroy, which makes my machines never start/stop.

A good create command looks like this
```
COMMAND: ansible-playbook --diff --inventory /home/t/.cache/molecule/playbook/default/inventory --skip-tags molecule-notest,notest /home/t/.local/lib/python3.8/site-packages/molecule_vagrant/playbooks/create.yml
```
With `ansible_args` it looks like that: 
```
COMMAND: ansible-playbook --diff --inventory /home/t/.cache/molecule/playbook/default/inventory --skip-tags molecule-notest,notest --become --tags=install /home/t/.local/lib/python3.8/site-packages/molecule_default/playbooks/create.yml
```
The create playbook doesn't do anything with just this tag.

I have reprodiced this with both vagrant and podman driver.

**Comment by t2d** [comment]
My current workaround is to apply tags manually to the converge step, but i would like to avoid this
```
cat molecule.yml
---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: opensuse15
    box: generic/opensuse15
  - name: debian10
    box: generic/debian10
provisioner:
  name: ansible
  playbooks:
    converge: ../../site.yml
verifier:
  name: ansible

molecule create
molecule converge -- -t install
molecule verify
molecule destroy
```

**Comment by t2d** [comment]
Thanks a lot!

**Comment by fletort** [comment]
I have a "bug ?" linked to this issue... I don't know if it is fixed with the given fix.... (to know if i open something for it or not).

In my case, it is prolbematic that the default "notest" tag is passed to create step.
In my create playbook, i am using a role to create some specific staff.... But this role was tested with molecule... and have some tasks with the given "notest" tag.... so the creation did not work, as theses tasks are not executed.....

For me theses specific tags should be passed only to converge step, no ?
It is the case with this fix or not ? (if not i will open a new issue)

**Comment by OlGe404** [comment]
**For those who need to pass config options to all steps and found this issue searching for a solution:** Use the config_options in the provisioner section of the molecule.yaml file.

I needed to pass a vault-keyring-script to all molecule steps and used ansible_args first, but as stated above that is not intended for this purpose.

Do it like this:
```
# molecule.yml
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_identity_list: <identity>@<path-to-keyring-scrpt>
```
