### ISSUE TITLE
Support for multiple verifiers

### ISSUE THREAD

**Issue by amarao** [ansible-community/molecule#3089]
# Issue Type

- Feature request

I'd like to discuss if it's within project ideology to support for multiple verifiers. Currently, every scenario is either testinfra or ansible, without ability to run both on the same scenario.

That's exactly a situation we got ourselves. We use molecule to test a large playbook, and it has tests both in a form of a playbook and in a form of testinfra tests. It's really hard to rewrite some of ansible tests to testinfra (as they uses a lot of ansible machinery) and it's really sad to rewrite nice pytest tests into playbooks.

I think about adding support of lists to `verifier` statement. Updated syntax would look like this:

```yaml
verifier:
  - name: testinfra
    additional_files_or_dirs:
      - ../path/to/test_1.py
  - name: ansible
    env:
      FOO: bar
```
Original single entry configuration would be supported as special case (dict instead of list).

Will such change be welcomed?
