### ISSUE TITLE
Docker image creation fails with molecule

### ISSUE THREAD

**Issue by lkalina-cera** [ansible-community/molecule#3187]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule 3.3.0 using python 3.7
    ansible:2.10.8
    delegated:3.3.0 from molecule
    docker:0.2.4 from molecule_docker
```

Molecule installation method (one of):

pip (in a venv)
Ansible installation method (one of):

pip (in a venv)

# Desired Behavior

Here is my simple project structure.
I would like to use the image for further work. 
```.
└── molecule
    └── default
        ├── Dockerfile
        ├── converge.yml
        ├── molecule.yml
        └── test_folder
            └── test_file
```
Dockerfile content
```
FROM centos:7

COPY test_folder /test_folder
```
converge-yml content
```
---
- name: Converge example
  hosts: localhost
  gather_facts: no
```

molecule.yml content
```
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: atestimage
    image: test/testimage:0.1
    dockerfile: Dockerfile
    pre_build_image: false
provisioner:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
    - destroy
  ```
In the command line I use `molecule create` and then the images should have created.
# Actual Behaviour

Image creations fails with the following message

> msg": "Error building molecule_local/test/testimage - code: None, message: COPY failed: stat /var/lib/docker/tmp/docker-builder598809966/test_folder: no such file or directory,

Please help me to identify whats the problem whit this.
