### ISSUE TITLE
[podman] space in platform name breaks image build

### ISSUE THREAD

**Issue by rkm** [ansible-community/molecule#3207]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible [core 2.11.2]
  ...
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.1
  libyaml = True
molecule 3.4.0 using python 3.8
    ansible:2.11.2
    delegated:3.4.0 from molecule
    docker:0.2.4 from molecule_docker
    podman:0.3.0 from molecule_podman
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:
- N/A

# Desired Behavior

With the config:

```yaml
---
driver:
  name: podman
platforms:
  - name: rocky 8.4
    image: docker.io/rockylinux/rockylinux:8.4
    privileged: true
  - name: ubuntu 20.04
    image: docker.io/ubuntu:20.04
    privileged: true
  - name: centos 8.3.2011
    image: docker.io/centos:8.3.2011
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
```

Molecule should build and run each image.

# Actual Behaviour

The spaces in each platform name seem to be parsed incorrectly, causing molecule to try and pull an invalid image from docker.io (`Trying to pull docker.io/library/8.3.2011:latest...`):

```console
failed: [localhost] (item={'started': 1, 'finished': 0, 'ansible_job_id': '991171847756.53015', 'results_file': '/home/rkm/.ansible_async/991171847756.53015', 'changed': True, 'failed': False, 'item': {'image': 'docker.io/centos:8.3.2011', 'name': 'centos 8.3.2011', 'privileged': True}, 'ansible_loop_var': 'item'}) => {"ansible_job_id": "991171847756.53015", "ansible_loop_var": "item", "attempts": 1, "changed": true, "cmd": ["podman", "run", "-d", "--name", "centos 8.3.2011", "--privileged=True", "--hostname=centos", "8.3.2011", "molecule_local/docker.io/centos:8.3.2011", "bash", "-c", "while true; do sleep 10000; done"], "delta": "0:00:01.405146", "end": "2021-08-14 23:17:52.366322", "finished": 1, "item": {"ansible_job_id": "991171847756.53015", "ansible_loop_var": "item", "changed": true, "failed": false, "finished": 0, "item": {"image": "docker.io/centos:8.3.2011", "name": "centos 8.3.2011", "privileged": true}, "results_file": "/home/rkm/.ansible_async/991171847756.53015", "started": 1}, "msg": "non-zero return code", "rc": 125, "start": "2021-08-14 23:17:50.961176", "stderr": "Resolving \"8.3.2011\" using unqualified-search registries (/home/rkm/.config/containers/registries.conf)\nTrying to pull docker.io/library/8.3.2011:latest...\nError: Error initializing source docker://8.3.2011:latest: Error reading manifest latest in docker.io/library/8.3.2011: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required", "stderr_lines": ["Resolving \"8.3.2011\" using unqualified-search registries (/home/rkm/.config/containers/registries.conf)", "Trying to pull docker.io/library/8.3.2011:latest...", "Error: Error initializing source docker://8.3.2011:latest: Error reading manifest latest in docker.io/library/8.3.2011: errors:", "denied: requested access to the resource is denied", "unauthorized: authentication required"], "stdout": "", "stdout_lines": []}
```
