### ISSUE TITLE
`verify` stage does not inherit role defaults

### ISSUE THREAD

**Issue by konstruktoid** [ansible-community/molecule#3587]
# Issue Type

- Bug report

# Molecule and Ansible details

```bash
ansible [core 2.14.0.dev0]
  config file = None
  configured module search path = ['[...]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = [...]/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:28:31) [Clang 13.1.6 (clang-1316.0.21.2)] (/usr/local/opt/python@3.9/bin/python3.9)
  jinja version = 3.0.2
  libyaml = True
```

```bash
molecule 4.0.0a1.dev12 using python 3.9
    ansible:2.14.0.dev0
    delegated:4.0.0a1.dev12 from molecule
    podman:1.0.1 from molecule_podman requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:1.0.1.dev14 from molecule_vagrant
```

Molecule installation method (one of):

- pip installation of github main

Ansible installation method (one of):

- pip installation of github main

Detail any linters or test runners used:

```yaml
lint: |
  set -e
  ansible-lint
```

# Desired Behavior

The verification stage should inherit role defaults.

# Actual Behaviour

The verification stage does not inherit role defaults, causing an `is undefined` error.

```bash
.
├── README.md
├── defaults
│   └── main
│       └── main.yml
├── molecule
│   └── default
│       ├── INSTALL.rst
│       ├── converge.yml
│       ├── molecule.yml
│       └── verify.yml
├── tasks
│   └── main.yml
└── templates

6 directories, 7 files
```

`defaults/main/main.yml`:
```yaml
---
message: "shiny_pikachu"
another_message: "psychic_mewtwo"
change_message: false
...
```

`tasks/main.yml`:
```yaml
---
- name: print message
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items:
    - "{{ message }}"
    - "{{ another_message }}"
    - "{{ change_message }}"

- name: assert jammy01
  ansible.builtin.assert:
    that:
      - message ==  "shiny_pikachu"
  when: ansible_hostname == "jammy01"

- name: assert jammy02
  ansible.builtin.assert:
    that:
      - message ==  "replaced_message"
  when: ansible_hostname == "jammy02"

- name: assert jammy03
  ansible.builtin.assert:
    that:
      - another_message ==  "psychic_mewtwo"
  when: ansible_hostname == "jammy03"

- name: write a message
  ansible.builtin.lineinfile:
    path: '/tmp/pokedex'
    line: "{{ message }}"
    state: present
    create: true
    mode: "0666"
  when: not change_message

- name: write another message
  ansible.builtin.lineinfile:
    path: '/tmp/pokedex'
    line: "{{ another_message }}"
    state: present
    create: true
    mode: "0666"
  when: change_message
...
```

`molecule/default/molecule.yml`:
```yaml
---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
  provider_options:
    linked_clone: false
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      jammy02:
        change_message: true
        message: "replaced_message"
      jammy03:
        change_message: true
platforms:
  - name: jammy01
    box: "ubuntu/jammy64"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: jammy02
    box: "ubuntu/jammy64"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: jammy03
    box: "ubuntu/jammy64"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
scenario:
  name: default
[...]
```

`molecule/default/verify.yml`:
```yaml
# message: "shiny_pikachu"
# another_message: "psychic_mewtwo"
# change_message: false

#    host_vars:
#      jammy02:
#        change_message: true
#        message: "replaced_message"
#      jammy03:
#        change_message: true
---
- name: Verify
  hosts: all
  tasks:
    - name: verification - print message
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items:
        - "{{ message }}"
        - "{{ another_message }}"
        - "{{ change_message }}"

    - name: verification - assert jammy01
      ansible.builtin.assert:
        that:
          - message ==  "shiny_pikachu"
      when: ansible_hostname == "jammy01"

    - name: verification - assert jammy02
      ansible.builtin.assert:
        that:
          - message ==  "replaced_message"
      when: ansible_hostname == "jammy02"

    - name: verification - assert jammy03
      ansible.builtin.assert:
        that:
          - message ==  "psychic_mewtwo"
      when: ansible_hostname == "jammy03"
...
```

```bash
WARNING: PATH altered to include /usr/local/opt/python@3.9/bin
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [Destroy] *****************************************************************

TASK [Destroy molecule instance(s)] ********************************************
Monday 13 June 2022  23:28:32 +0200 (0:00:00.023)       0:00:00.023 ***********
ok: [localhost]

TASK [Populate instance config] ************************************************
Monday 13 June 2022  23:28:40 +0200 (0:00:07.838)       0:00:07.862 ***********
ok: [localhost]

TASK [Dump instance config] ****************************************************
Monday 13 June 2022  23:28:40 +0200 (0:00:00.085)       0:00:07.947 ***********
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

Monday 13 June 2022  23:28:40 +0200 (0:00:00.080)       0:00:08.028 ***********
===============================================================================
Destroy molecule instance(s) -------------------------------------------- 7.84s
Populate instance config ------------------------------------------------ 0.09s
Dump instance config ---------------------------------------------------- 0.08s
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

playbook: [...]/issue-molecule-defaults/molecule/default/converge.yml
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [Create] ******************************************************************

TASK [Create molecule instance(s)] *********************************************
Monday 13 June 2022  23:28:42 +0200 (0:00:00.023)       0:00:00.023 ***********
changed: [localhost]

TASK [Populate instance config dict] *******************************************
Monday 13 June 2022  23:30:39 +0200 (0:01:57.232)       0:01:57.255 ***********
ok: [localhost] => (item={'Host': 'jammy01', 'HostName': '127.0.0.1', 'User': 'vagrant', 'Port': '2201', 'UserKnownHostsFile': '/dev/null', 'StrictHostKeyChecking': 'no', 'PasswordAuthentication': 'no', 'IdentityFile': '[...]/.cache/molecule/issue-molecule-defaults/default/.vagrant/machines/jammy01/virtualbox/private_key', 'IdentitiesOnly': 'yes', 'LogLevel': 'FATAL'})
ok: [localhost] => (item={'Host': 'jammy02', 'HostName': '127.0.0.1', 'User': 'vagrant', 'Port': '2202', 'UserKnownHostsFile': '/dev/null', 'StrictHostKeyChecking': 'no', 'PasswordAuthentication': 'no', 'IdentityFile': '[...]/.cache/molecule/issue-molecule-defaults/default/.vagrant/machines/jammy02/virtualbox/private_key', 'IdentitiesOnly': 'yes', 'LogLevel': 'FATAL'})
ok: [localhost] => (item={'Host': 'jammy03', 'HostName': '127.0.0.1', 'User': 'vagrant', 'Port': '2203', 'UserKnownHostsFile': '/dev/null', 'StrictHostKeyChecking': 'no', 'PasswordAuthentication': 'no', 'IdentityFile': '[...]/.cache/molecule/issue-molecule-defaults/default/.vagrant/machines/jammy03/virtualbox/private_key', 'IdentitiesOnly': 'yes', 'LogLevel': 'FATAL'})

TASK [Convert instance config dict to a list] **********************************
Monday 13 June 2022  23:30:39 +0200 (0:00:00.172)       0:01:57.428 ***********
ok: [localhost]

TASK [Dump instance config] ****************************************************
Monday 13 June 2022  23:30:39 +0200 (0:00:00.082)       0:01:57.511 ***********
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Monday 13 June 2022  23:30:40 +0200 (0:00:01.156)       0:01:58.668 ***********
===============================================================================
Create molecule instance(s) ------------------------------------------- 117.23s
Dump instance config ---------------------------------------------------- 1.16s
Populate instance config dict ------------------------------------------- 0.17s
Convert instance config dict to a list ---------------------------------- 0.08s
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [Prepare] *****************************************************************

TASK [Bootstrap python for Ansible] ********************************************
Monday 13 June 2022  23:30:42 +0200 (0:00:00.042)       0:00:00.042 ***********
ok: [jammy02]
ok: [jammy03]
ok: [jammy01]

PLAY RECAP *********************************************************************
jammy01                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
jammy02                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
jammy03                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Monday 13 June 2022  23:30:44 +0200 (0:00:01.266)       0:00:01.309 ***********
===============================================================================
Bootstrap python for Ansible -------------------------------------------- 1.27s
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [Converge] ****************************************************************

TASK [Gathering Facts] *********************************************************
Monday 13 June 2022  23:30:45 +0200 (0:00:00.059)       0:00:00.059 ***********
ok: [jammy02]
ok: [jammy01]
ok: [jammy03]

TASK [Include issue-molecule-defaults] *****************************************
Monday 13 June 2022  23:30:47 +0200 (0:00:01.969)       0:00:02.028 ***********

TASK [issue-molecule-defaults : print message] *********************************
Monday 13 June 2022  23:30:47 +0200 (0:00:00.132)       0:00:02.161 ***********
ok: [jammy01] => (item=shiny_pikachu) => {
    "msg": "shiny_pikachu"
}
ok: [jammy01] => (item=psychic_mewtwo) => {
    "msg": "psychic_mewtwo"
}
ok: [jammy01] => (item=False) => {
    "msg": false
}
ok: [jammy02] => (item=replaced_message) => {
    "msg": "replaced_message"
}
ok: [jammy02] => (item=psychic_mewtwo) => {
    "msg": "psychic_mewtwo"
}
ok: [jammy03] => (item=shiny_pikachu) => {
    "msg": "shiny_pikachu"
}
ok: [jammy02] => (item=True) => {
    "msg": true
}
ok: [jammy03] => (item=psychic_mewtwo) => {
    "msg": "psychic_mewtwo"
}
ok: [jammy03] => (item=True) => {
    "msg": true
}

TASK [issue-molecule-defaults : assert jammy01] ********************************
Monday 13 June 2022  23:30:47 +0200 (0:00:00.141)       0:00:02.302 ***********
skipping: [jammy02]
ok: [jammy01] => {
    "changed": false,
    "msg": "All assertions passed"
}
skipping: [jammy03]

TASK [issue-molecule-defaults : assert jammy02] ********************************
Monday 13 June 2022  23:30:47 +0200 (0:00:00.080)       0:00:02.383 ***********
skipping: [jammy01]
ok: [jammy02] => {
    "changed": false,
    "msg": "All assertions passed"
}
skipping: [jammy03]

TASK [issue-molecule-defaults : assert jammy03] ********************************
Monday 13 June 2022  23:30:47 +0200 (0:00:00.087)       0:00:02.470 ***********
skipping: [jammy01]
skipping: [jammy02]
ok: [jammy03] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [issue-molecule-defaults : write a message] *******************************
Monday 13 June 2022  23:30:47 +0200 (0:00:00.116)       0:00:02.587 ***********
skipping: [jammy02]
skipping: [jammy03]
changed: [jammy01]

TASK [issue-molecule-defaults : write another message] *************************
Monday 13 June 2022  23:30:48 +0200 (0:00:00.677)       0:00:03.265 ***********
skipping: [jammy01]
changed: [jammy02]
changed: [jammy03]

PLAY RECAP *********************************************************************
jammy01                    : ok=4    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
jammy02                    : ok=4    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
jammy03                    : ok=4    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0

Monday 13 June 2022  23:30:49 +0200 (0:00:00.586)       0:00:03.851 ***********
===============================================================================
Gathering Facts --------------------------------------------------------- 1.97s
issue-molecule-defaults : write a message ------------------------------- 0.68s
issue-molecule-defaults : write another message ------------------------- 0.59s
issue-molecule-defaults : print message --------------------------------- 0.14s
Include issue-molecule-defaults ----------------------------------------- 0.13s
issue-molecule-defaults : assert jammy03 -------------------------------- 0.12s
issue-molecule-defaults : assert jammy02 -------------------------------- 0.09s
issue-molecule-defaults : assert jammy01 -------------------------------- 0.08s
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [Converge] ****************************************************************

TASK [Gathering Facts] *********************************************************
Monday 13 June 2022  23:30:50 +0200 (0:00:00.060)       0:00:00.060 ***********
ok: [jammy02]
ok: [jammy01]
ok: [jammy03]

TASK [Include issue-molecule-defaults] *****************************************
Monday 13 June 2022  23:30:51 +0200 (0:00:01.639)       0:00:01.700 ***********

TASK [issue-molecule-defaults : print message] *********************************
Monday 13 June 2022  23:30:51 +0200 (0:00:00.129)       0:00:01.829 ***********
ok: [jammy01] => (item=shiny_pikachu) => {
    "msg": "shiny_pikachu"
}
ok: [jammy01] => (item=psychic_mewtwo) => {
    "msg": "psychic_mewtwo"
}
ok: [jammy02] => (item=replaced_message) => {
    "msg": "replaced_message"
}
ok: [jammy01] => (item=False) => {
    "msg": false
}
ok: [jammy02] => (item=psychic_mewtwo) => {
    "msg": "psychic_mewtwo"
}
ok: [jammy03] => (item=shiny_pikachu) => {
    "msg": "shiny_pikachu"
}
ok: [jammy02] => (item=True) => {
    "msg": true
}
ok: [jammy03] => (item=psychic_mewtwo) => {
    "msg": "psychic_mewtwo"
}
ok: [jammy03] => (item=True) => {
    "msg": true
}

TASK [issue-molecule-defaults : assert jammy01] ********************************
Monday 13 June 2022  23:30:52 +0200 (0:00:00.145)       0:00:01.975 ***********
ok: [jammy01] => {
    "changed": false,
    "msg": "All assertions passed"
}
skipping: [jammy02]
skipping: [jammy03]

TASK [issue-molecule-defaults : assert jammy02] ********************************
Monday 13 June 2022  23:30:52 +0200 (0:00:00.089)       0:00:02.064 ***********
skipping: [jammy01]
ok: [jammy02] => {
    "changed": false,
    "msg": "All assertions passed"
}
skipping: [jammy03]

TASK [issue-molecule-defaults : assert jammy03] ********************************
Monday 13 June 2022  23:30:52 +0200 (0:00:00.092)       0:00:02.157 ***********
skipping: [jammy01]
skipping: [jammy02]
ok: [jammy03] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [issue-molecule-defaults : write a message] *******************************
Monday 13 June 2022  23:30:52 +0200 (0:00:00.113)       0:00:02.270 ***********
skipping: [jammy02]
skipping: [jammy03]
ok: [jammy01]

TASK [issue-molecule-defaults : write another message] *************************
Monday 13 June 2022  23:30:53 +0200 (0:00:00.667)       0:00:02.938 ***********
skipping: [jammy01]
ok: [jammy02]
ok: [jammy03]

PLAY RECAP *********************************************************************
jammy01                    : ok=4    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
jammy02                    : ok=4    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
jammy03                    : ok=4    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0

Monday 13 June 2022  23:30:53 +0200 (0:00:00.705)       0:00:03.643 ***********
===============================================================================
Gathering Facts --------------------------------------------------------- 1.64s
issue-molecule-defaults : write another message ------------------------- 0.71s
issue-molecule-defaults : write a message ------------------------------- 0.67s
issue-molecule-defaults : print message --------------------------------- 0.15s
Include issue-molecule-defaults ----------------------------------------- 0.13s
issue-molecule-defaults : assert jammy03 -------------------------------- 0.11s
issue-molecule-defaults : assert jammy02 -------------------------------- 0.09s
issue-molecule-defaults : assert jammy01 -------------------------------- 0.09s
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [Verify] ******************************************************************

TASK [Gathering Facts] *********************************************************
Monday 13 June 2022  23:30:54 +0200 (0:00:00.017)       0:00:00.017 ***********
ok: [jammy02]
ok: [jammy03]
ok: [jammy01]

TASK [verification - print message] ********************************************
Monday 13 June 2022  23:30:56 +0200 (0:00:01.589)       0:00:01.606 ***********
fatal: [jammy01]: FAILED! => {"msg": "'message' is undefined"}
fatal: [jammy02]: FAILED! => {"msg": "'another_message' is undefined"}
fatal: [jammy03]: FAILED! => {"msg": "'message' is undefined"}

PLAY RECAP *********************************************************************
jammy01                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
jammy02                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
jammy03                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Monday 13 June 2022  23:30:56 +0200 (0:00:00.080)       0:00:01.687 ***********
===============================================================================
Gathering Facts --------------------------------------------------------- 1.59s
verification - print message -------------------------------------------- 0.08s
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [Destroy] *****************************************************************

TASK [Destroy molecule instance(s)] ********************************************
Monday 13 June 2022  23:30:57 +0200 (0:00:00.023)       0:00:00.023 ***********
changed: [localhost]

TASK [Populate instance config] ************************************************
Monday 13 June 2022  23:31:31 +0200 (0:00:34.137)       0:00:34.160 ***********
ok: [localhost]

TASK [Dump instance config] ****************************************************
Monday 13 June 2022  23:31:31 +0200 (0:00:00.084)       0:00:34.244 ***********
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Monday 13 June 2022  23:31:32 +0200 (0:00:01.110)       0:00:35.356 ***********
===============================================================================
Destroy molecule instance(s) ------------------------------------------- 34.14s
Dump instance config ---------------------------------------------------- 1.11s
Populate instance config ------------------------------------------------ 0.08s
```

**Comment by zhan9san** [comment]
I'll look into this issue.

**Comment by zhan9san** [comment]
Hi @konstruktoid 

It can be reproduced. But I don't think it's a bug.

When verifier is `ansible`, `verify.yml` acts as a playbook and be invoked by `molecule`. To be more exact, `molecule` executes `ansible-playbook --inventory xxx xxx/verify.yml`.

The variables defined in `defaults/main.yml` is found by `ansible` instead of `molecule`, referring to [[Understanding variable precedence](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#id40)](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence)

Currently, `molecule converge` works well. Because it does not refer default variables directly, the included role will refer those variables as below.

```yml
    - name: "Include acme.my_new_role_docker"
      include_role:
        name: "acme.my_new_role_docker"
```

If we refer to those variables in `converge.yml` directly, the same error will occur.

```yml
---
- name: Converge
  hosts: all
  tasks:
    - name: Converge verification - print message
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items:
        - "{{ message }}"
        - "{{ another_message }}"
        - "{{ change_message }}"
    - name: "Include acme.my_new_role_docker"
      include_role:
        name: "acme.my_new_role_docker"
```

Besides, if we want to verify/assert something, it's fun to use a hard-code value in the expected variable.

Does it make sense?

**Comment by konstruktoid** [comment]
> Besides, if we want to verify/assert something, it's fun to use a hard-code value in the expected variable.

"Fun" might not be the word I would use, and why duplicate multiple variables (which is needed when hard coding) instead of a flexible system, allowing to test both the defaults and `host_vars`?

**Comment by zhan9san** [comment]
`defaults/main.yml`, indeed is a part of role, and it's not safe. So I don't think we should assert things based on it.

If we execute the role, how do we know whether variables defined in `defaults/main.yml` are not modified by some other logic.

> why duplicate multiple variables (which is needed when hard-coding every single thing) instead of a flexible system

It's similar to integration test. We don't know whether variables referred from business code is safe, so we define another separated variables in test code.

If one single hard-code variable is referred in many tasks, we can set it at the top of playbook, [defining-variables-in-a-play](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-a-play)

```
- hosts: webservers
  vars:
    foo: bar
```

**Comment by konstruktoid** [comment]
> If we execute the role, how do we know whether variables defined in `defaults/main.yml` are not modified by some other logic.

That is one of the points, they are, by using `host_vars`. And `host_vars` are set so multiple variations of a role can be tested (but currently not verified).

> We don't know whether variables referred from business code is safe

Please elaborate.

**Comment by zhan9san** [comment]
As we can see, the values of those variables defined by default are mutable. 

Let us take "foo: bar" in default/main.yml as an example, and baz is a variable to be verified.

If the assertion "{{ foo }}" == baz doesn't work as expected, we need to identify whether "foo" is modified somewhere.

How about using "bar" == baz explicitly?

It does introduce a duplicate definition, but  explicit is better than implicit.

Besides, as I mentioned, it's a part of role, the assertion based its own variables is not credible.

Looking forward to your new comments.

**Comment by konstruktoid** [comment]
The main issue is that if a task writes `{{ message }}` to file `x`, I'd assume I can `assert` or other ways test that `{{ message }}` has indeed been written to file `x`. No matter what the actual `{{ message }}` is.

**Comment by zhan9san** [comment]
>  test that {{ message }} has indeed been written to file x. No matter what the actual {{ message }} is.

If you don't care what value is in file `x`, we can just check whether file `x` exist or is it a blank file.

If you want to check the real content in file `x`, it's better to use an explicit string instead of a mutable variable.

**Comment by konstruktoid** [comment]
> If you want to check the real content in file `x`, it's better to use an explicit string instead of a mutable variable.

Yeah, I hear you but adding a hundred defined variables in molecule in order to test explicit strings, especially when the `host_vars` are meant to modify which tasks are executed seems like a lot of wasted time.

**Comment by konstruktoid** [comment]
I totally agree with you and understand what you are saying regarding mutable variables, but we are not testing a system (or file in this case) subject to an multi-user or multi-application environment.

The testing is done on a single role in a pre-defined static environment (the git repository), but where the variables are mutable and possibly changed by `host_vars` in order to test different scenarios.

This doesn't have to be a reproducible build or strict unit testing.

**Comment by konstruktoid** [comment]
For future references:

```yaml
---
- name: Verify
  hosts: all
  any_errors_fatal: true

    - name: include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_hostname }}"
...
```
