### ISSUE TITLE
Running side effect with custom playbook skips when no default is defined

### ISSUE THREAD

**Issue by saiello** [ansible-community/molecule#3617]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```

```
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/Users/saiello/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/saiello/Workspace/github.com/tmp-molecule-bug/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/saiello/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/saiello/Workspace/github.com/tmp-molecule-bug/venv/bin/ansible
  python version = 3.10.3 (main, Jul 17 2022, 16:04:39) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.1.2
  libyaml = True
molecule 4.0.0 using python 3.10 
    ansible:2.13.1
    delegated:4.0.0 from molecule
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# How to reproduce

```
molecule init scenario
mv molecule/default/verify{,_reboot}.yml
cat <<\EOF > molecule/default/molecule.yml
---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
    - idempotence
    - side_effect reboot.yml
    - verify verify_reboot.yml
EOF

molecule converge
```

# Desired Behavior

Configuring a custom playbook for side_effect should run that playbook despite the presence of the default `provisioner.playbooks.side_effect` value. 

In the mcve the reboot.yml playbook is expected to be executed.

# Actual Behaviour

Side effect is skipped with the following output:

```
INFO     Running default > side_effect
WARNING  Skipping, side effect playbook not configured.
```

**Comment by amarao** [comment]
I've missed that. As workaround, just create an empty side_effect.yml file.

I will try to find a fix.

**Comment by saiello** [comment]
> I've missed that. As workaround, just create an empty side_effect.yml file.

Yeah it works. Thanks!

> I will try to find a fix.

If can help, the verify is working as expected.

**Comment by trallnag** [comment]
@noonedeadpunk it works for me with the empty file.

<img width="674" height="301" alt="Image" src="https://github.com/user-attachments/assets/c40644e2-4428-48a0-9198-4fe8fa4360a8" />

[logs.txt](https://github.com/user-attachments/files/21198861/logs.txt)

**Comment by noonedeadpunk** [comment]
Ok, so I tested this thing one more time just now with same effect pretty much...

```
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: "${MOLECULE_SCENARIO_NAME}"
    image: "${DOCKER_REGISTRY:-quay.io/gotmax23}/${DOCKER_IMAGE_TAG:-debian-systemd:bookworm}"
    command: ${DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    systemd: true
    groups:
      - service_hosts

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../../tests/prepare.yml
    converge: ../../tests/test.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify ../../tests/verify.yml
    - side_effect ../../tests/test_service_updates.yml
    - verify ../../tests/verify_service_updates.yml
    - cleanup
    - destroy
 ```

And then listings:
```
$ ls -l tests/
total 20
-rw-rw-r-- 1 dr5005 dr5005  293 Aug  8 14:31 prepare.yml
-rw-rw-r-- 1 dr5005 dr5005    0 Aug  8 14:20 test_service_updates.yml
-rw-rw-r-- 1 dr5005 dr5005 1280 Aug  8 14:26 test-vars.yml
-rw-rw-r-- 1 dr5005 dr5005  736 Aug  8 14:17 test.yml
-rw-rw-r-- 1 dr5005 dr5005  289 Aug  8 14:22 verify_service_updates.yml
-rw-rw-r-- 1 dr5005 dr5005  293 Aug  8 14:22 verify.yml
$ ls -l molecule/default/
total 4
-rw-rw-r-- 1 dr5005 dr5005 938 Aug  8 14:30 molecule.yml
-rw-rw-r-- 1 dr5005 dr5005   0 Aug  8 14:37 side_effect.yml
```

This results in a failure for me:
```
INFO     Verifier completed successfully.
INFO     Running default > side_effect
ERROR! Empty playbook, nothing to do: molecule/default/side_effect.yml
CRITICAL Ansible return code was 4
```

In case I add some noop task into `molecule/default/side_effect.yml` - it is executed instead of `../../tests/test_service_updates.yml` which is just ignored:
```
INFO     Verifier completed successfully.
INFO     Running default > side_effect

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

INFO     Running default > verify
INFO     Running Ansible Verifier
```

So I really not sure what/how I can make multiple side-effects to work...
