### ISSUE TITLE
Problem during "Determine the CMD directives" with environment variable substituion

### ISSUE THREAD

**Issue by LorenzoBettini** [ansible-community/molecule#3677]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule 4.0.1 using python 3.10 
    ansible:2.13.4
    delegated:4.0.1 from molecule
    docker:2.1.0 from molecule_docker requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

My CI GitHub Actions job for my ansible playbook recently started to fail during the `create` phase.
I have a custom Dockerfile and in my `molecule.yml` I have this part

```yaml
platforms:
  - name: "${MOLECULE_DISTRO:-arch-gnome}-instance"
    image: "custom-${MOLECULE_DISTRO:-arch-gnome}-ansible"
    dockerfile: ../docker/Dockerfile
    command: ""
    privileged: true
    build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../${MOLECULE_DISTRO:-arch-gnome}/converge.yml
verifier:
  name: ansible
```

The GitHub Actions job is of the shape (only the interesting parts are shown):

```yaml
jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        playbookdistro:
          - arch-gnome
          - arch-kde
...
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.playbookdistro }}
```

This way, I can run molecule against two different playbooks, where each playbook uses a different Docker image name (starting from the same Dockerfile), see the `MOLECULE_DISTRO` environment variable. That is highly inspired by @geerlingguy 

This was working perfectly a few days ago. In particular, in the `create` stage I could see in the LOG that the environment variable was correctly expanded. For example, when the `MOLECULE_DISTRO` is `arch-kde` I could see in the log (note that `arch-kde` was correctly replaced)

```
  TASK [Check presence of custom Dockerfiles] ************************************
  ok: [localhost] => (item={'build_image': True, 'command': '', 'dockerfile': '../docker/Dockerfile', 'image': 'custom-arch-kde-ansible', 'name': 'arch-kde-instance', 'privileged': True})

  TASK [Create Dockerfiles from image names] *************************************
  changed: [localhost] => (item={'build_image': True, 'command': '', 'dockerfile': '../docker/Dockerfile', 'image': 'custom-arch-kde-ansible', 'name': 'arch-kde-instance', 'privileged': True})

  TASK [Discover local Docker images] ********************************************
...
  TASK [Build an Ansible compatible image (new)] *********************************
  changed: [localhost] => (item=molecule_local/custom-arch-kde-ansible)
...
  TASK [Determine the CMD directives] ********************************************
  ok: [localhost] => (item={'build_image': True, 'command': '', 'dockerfile': '../docker/Dockerfile', 'image': 'custom-arch-kde-ansible', 'name': 'arch-kde-instance', 'privileged': True})

  TASK [Create molecule instance(s)] *********************************************
  changed: [localhost] => (item=arch-kde-instance)

  TASK [Wait for instance(s) creation to complete] *******************************
  changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '396025129257.2768', 'results_file': '/home/runner/.ansible_async/396025129257.2768', 'changed': True, 'item': {'build_image': True, 'command': '', 'dockerfile': '../docker/Dockerfile', 'image': 'custom-arch-kde-ansible', 'name': 'arch-kde-instance', 'privileged': True}, 'ansible_loop_var': 'item'})
```

# Actual Behaviour

Today, the Docker image is correctly created, and in the first tasks, `MOLECULE_DISTRO` is correctly replaced with `arch-kde`, but from "Determine the CMD directives" on, the `MOLECULE_DISTRO` is not expanded anymore, of course leading to a failure because, the image has been created correctly, but when it tries to create the instance it uses an image name where `MOLECULE_DISTRO` has not been replaced. These are the tasks (the first ones are still correct but from "Determine the CMD directives" we have this problem:

```
TASK [Check presence of custom Dockerfiles] ************************************
  ok: [localhost] => (item={'build_image': True, 'command': '', 'dockerfile': '../docker/Dockerfile', 'image': 'custom-arch-kde-ansible', 'name': 'arch-kde-instance', 'privileged': True})
  
  TASK [Create Dockerfiles from image names] *************************************
  changed: [localhost] => (item={'build_image': True, 'command': '', 'dockerfile': '../docker/Dockerfile', 'image': 'custom-arch-kde-ansible', 'name': 'arch-kde-instance', 'privileged': True})
  
  TASK [Synchronization the context] *********************************************
  changed: [localhost] => (item={'build_image': True, 'command': '', 'dockerfile': '../docker/Dockerfile', 'image': 'custom-arch-kde-ansible', 'name': 'arch-kde-instance', 'privileged': True})
  
  TASK [Discover local Docker images] ********************************************
...
  TASK [Build an Ansible compatible image (new)] *********************************
  changed: [localhost] => (item=molecule_local/custom-arch-kde-ansible)
...  
  TASK [Create docker network(s)] ************************************************
```
**PROBLEMS START HERE**

```
  
  TASK [Determine the CMD directives] ********************************************
  ok: [localhost] => (item={'name': '${MOLECULE_DISTRO:-arch-gnome}-instance', 'image': 'custom-${MOLECULE_DISTRO:-arch-gnome}-ansible', 'dockerfile': '../docker/Dockerfile', 'command': '', 'privileged': True, 'build_image': True})
  
  TASK [Create molecule instance(s)] *********************************************
  changed: [localhost] => (item=${MOLECULE_DISTRO:-arch-gnome}-instance)
  
  TASK [Wait for instance(s) creation to complete] *******************************
  failed: [localhost] (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '166600780733.2927', 'results_file': '/home/runner/.ansible_async/166600780733.2927', 'changed': True, 'item': {'name': '${MOLECULE_DISTRO:-arch-gnome}-instance', 'image': 'custom-${MOLECULE_DISTRO:-arch-gnome}-ansible', 'dockerfile': '../docker/Dockerfile', 'command': '', 'privileged': True, 'build_image': True}, 'ansible_loop_var': 'item'}) => {"ansible_job_id": "166600780733.2927", "ansible_loop_var": "item", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "166600780733.2927", "ansible_loop_var": "item", "changed": true, "failed": 0, "finished": 0, "item": {"build_image": true, "command": "", "dockerfile": "../docker/Dockerfile", "image": "custom-${MOLECULE_DISTRO:-arch-gnome}-ansible", "name": "${MOLECULE_DISTRO:-arch-gnome}-instance", "privileged": true}, "results_file": "/home/runner/.ansible_async/166600780733.2927", "started": 1}, "msg": "Error pulling image molecule_local/custom-${MOLECULE_DISTRO:-arch-gnome}-ansible - 400 Client Error for http+docker://localhost/v1.41/images/create?tag=-arch-gnome%7D-ansible&fromImage=molecule_local%2Fcustom-%24%7BMOLECULE_DISTRO: Bad Request (\"invalid reference format: repository name must be lowercase\")", "results_file": "/home/runner/.ansible_async/166600780733.2927", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

I did not touch anything concerning this part in Molecule, so I could only guess it's a problem with the new version. I'm wondering whether @geerlingguy has the same problems if he tries to run the GitHub Actions CI, e.g., for https://github.com/geerlingguy/ansible-role-docker
