### ISSUE TITLE
Schema validation does not allow to specify side_effects and verify script

### ISSUE THREAD

**Issue by ehartmann** [ansible-community/molecule#3729]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible [core 2.13.5]
  config file = /home/eric/.ansible.cfg
  configured module search path = ['/home/eric/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/eric/.local/share/virtualenvs/ansible-role-teleport-4MgnzAtB/lib/python3.10/site-packages/ansible
  ansible collection location = /home/eric/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/eric/.local/share/virtualenvs/ansible-role-teleport-4MgnzAtB/bin/ansible
  python version = 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
molecule 4.0.3 using python 3.10 
    ansible:2.13.5
    delegated:4.0.3 from molecule
    docker:2.1.0 from molecule_docker requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

The schema validation should not block the usage of `side_effect` with parameters (https://molecule.readthedocs.io/en/latest/configuration.html#molecule.scenario.Scenario) in a test sequence : 
```yaml
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - lin
    - create
    - prepare
    - converge
    - idempotence
    - side_effect ../common/side_effects/create_admin_user.yml
    - verify
    - cleanup
    - destroy
```

# Actual Behaviour

As soon as we add the Ansible script to the `side_effect` or `verify`, molecule is refusing this configuration.
Here is the result :
```
> molecule test
CRITICAL Failed to validate /home/eric/my_role/molecule/default/molecule.yml

["'side_effect ../common/side_effects/create_admin_user.yml' is not one of ['check', 'cleanup', 'converge', 'create', 'dependency', 'destroy', 'idempotence', 'lint', 'prepare', {'type': 'string', 'pattern': 'side_effect .*'}, 'syntax', 'test', 'verify']"]
```
