### ISSUE TITLE
Failed to create temporary directory

### ISSUE THREAD

**Issue by mabed-fr** [ansible-community/molecule#3818]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Actual Behaviour

PLAY [Prepare] *****************************************************************

```
TASK [Gathering Facts] *********************************************************
fatal: [bookworm]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1674825123.6768813-82852-281344622743994 `\" && echo ansible-tmp-1674825123.6768813-82852-281344622743994=\"` echo ~/.ansible/tmp/ansible-tmp-1674825123.6768813-82852-281344622743994 `\" ), exited with result 1", "unreachable": true}
fatal: [bullseye]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1674825123.6879113-82853-251487814663029 `\" && echo ansible-tmp-1674825123.6879113-82853-251487814663029=\"` echo ~/.ansible/tmp/ansible-tmp-1674825123.6879113-82853-251487814663029 `\" ), exited with result 1", "unreachable": true}
fatal: [buster]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1674825123.7105093-82854-194659650698251 `\" && echo ansible-tmp-1674825123.7105093-82854-194659650698251=\"` echo ~/.ansible/tmp/ansible-tmp-1674825123.7105093-82854-194659650698251 `\" ), exited with result 1", "unreachable": true}
```

rm -rf /root/.cache/molecule

**Comment by javanaut-de** [comment]
This occurs for me when running role tests with Jenkins on a number of worker nodes using the podman driver and different OS images. Could this be some timing problem like container is not ready up when trying to access? Current workaround is to repeat failed tests a couple of times, which "works" most times as the error does not seem to depend on either the used OS image, worker node, scenario or time of the day.

Also this annoys hell out of me as I try to find a cause or solution for a couple of weeks now.

**Comment by javanaut-de** [comment]
Finally, after switching to a [set of static built executables](https://github.com/mgoltzsche/podman-static) of podman and its dependencies the issue seems having stopped to appear (for now ...)

**Comment by atj** [comment]
I was running into this issue on a new role when invoking Molecule via GitHub Actions. Turned out I had accidentally copied in an old version of `molecule.yml` from another role which was missing a couple of `platforms` options:

```yaml
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
```

Changing the cgroup volume to `rw` and adding `cgroupns_mode: host` resolved the issue for me:

```yaml
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
```

**Comment by calillo** [comment]
I have similar issue on Mac (but also on Windows it's the same) when running molecule inside container (with Docker Desktop). After spending a lot of time trying downgrading versions I realized that the cause was to be found elsewhere and found it in Docker Desktop, in fact natively on Mac (or on the Windows WSL) it worked perfectly.
At first, the reasoning was not clear to me but after reading some kernel intuition I realized it could be something like this. In fact months ago everything works and at some point it stopped and returning the error "failed to resolve remote temporary directory ... returned empty string"
From here I found out that since Docker Desktop 4.13 they upgraded the kernel from 5.10.x to 5.15.x and this is the root cause. Downgrading Docker Desktop to 4.12 on both Mac and Windows everything started working again. I think this problem also exists on a Linux distribution with a kernel 5.15.x, I can't tell if it's an incompatibility between ansible/molecule and the kernel. I hope someone fix this issue.

**Comment by Frzk** [comment]
I noticed something interesting in the documentation, here: https://ansible.readthedocs.io/projects/molecule/docker/#create-playbook :

```yaml
# we want to avoid errors like "Failed to create temporary directory"
- name: Validate that inventory was refreshed
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Display uname info
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
```

How do these tasks prevent the "Failed to create temporary directory" error?
Would it be possible for someone to elaborate a bit please? 🙏

**Comment by bataliero** [comment]
I have the same error message:
```
fatal: [instance]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1698921867.2522438-37545-235208512047875 `\" && echo ansible-tmp-1698921867.2522438-37545-235208512047875=\"` echo ~/.ansible/tmp/ansible-tmp-1698921867.2522438-37545-235208512047875 `\" ), exited with result 1", "unreachable": true}
```

versions:
```
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/home/mynia/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mynia/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mynia/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mynia/.local/bin/ansible
  python version = 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] (/usr/bin/python3.10)
  jinja version = 3.1.2
  libyaml = False
molecule 6.0.2 using python 3.10
    ansible:2.15.5
    azure:23.5.0 from molecule_plugins
    containers:23.5.0 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
    default:6.0.2 from molecule
    docker:23.5.0 from molecule_plugins requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
    ec2:23.5.0 from molecule_plugins
    gce:23.5.0 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
    podman:23.5.0 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:23.5.0 from molecule_plugins
```

OS -Linux Mint :
```
Distributor ID: Linuxmint
Description:    Linux Mint 20.3
Release:        20.3
Codename:       una
```

1. `molecule test` does not work if I use `podman` as a driver, and it does not work with `docker` as well
2. molecule destroy does no help
3. Changing molecule.yaml - cgroup volume to `rw` and adding `cgroupns_mode: host` does not help

Any other ideas?

**Comment by waterkip** [comment]
I have the same error, but ONLY if I have `command:` in the `molecule/default/molecule.yml`. When this isn't there I don't get the error. Although other errors occur at that point in relation to systemd.

**Comment by Nurlan199206** [comment]
help me pls too, i got same issue

```
TASK [community.docker.docker_container_exec] **********************************
fatal: [instance]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1705739384.2542112-6117-205789851287293 `\" && echo ansible-tmp-1705739384.2542112-6117-205789851287293=\"` echo ~/.ansible/tmp/ansible-tmp-1705739384.2542112-6117-205789851287293 `\" ), exited with result 1", "unreachable": true}
```

```
cat converge.yml
---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"

    - community.docker.docker_container_exec:
       container: hello-world
       command: df
```

**Comment by sdarwin** [comment]
I was just updating multiple roles. an earlier molecule.yml functioned on many of them:

```
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
    pre_build_image: true
```

then hit this "failed to create temporary directory" for one repo. why only one repo? It required the suggested updated:

```
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
```

Could molecule run a pre-flight check, determine if the bug will happen, and issue a warning which is not "failed to create a temporary directory"?

**Comment by cschindlbeck** [comment]
Even with `cgroupns_mode: host`, this issue still persists for me

**Comment by taylor-schneider** [comment]
I am seeing the same issue on almalinux 9.2

**Comment by mostwanted7** [comment]
Still seeing the same issue, tried every proposed solution but no luck.

**Comment by turb0bur** [comment]
Try removing the `create.yml` file located in the same folder as your `molecule.yml` file.
It helped me.
From what I understand, it contains an old workaround for gathering facts. 
I found this solution [here](https://github.com/ansible/molecule/issues/3094#issuecomment-1740751291).

**Comment by Kraktorist** [comment]
the same issue happens if the container we work with is stopped by the time of working with it. If so you should see it with the ANSIBLE_VERBOSITY=3

**Comment by d-mankowski-synerise** [comment]
I was able to run the exact same Molecule test without a problem, and encountered the problem on both macOS and Windows (WSL2). The clear common denominator was Docker Desktop and what was bothering me, is that I didn't see any containers in the output of `docker ps`. Turns out, Molecule does not support Docker contexts and `default` context must be used. And Docker Desktop uses `desktop-linux` by default.

`docker context ls` -> if the `*` is next to anything other than default, then execute `docker context use default`.

After doing that, I got an error:

```
Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1750887837.918037-63026-77324001976146 `\" && echo ansible-tmp-1750887837.918037-63026-77324001976146=\"` echo ~/.ansible/tmp/ansible-tmp-1750887837.918037-63026-77324001976146 `\" ), exited with result 1, stderr output: Error response from daemon: unable to find user dmankowski: no matching entries in passwd file\n
```

```
unable to find user dmankowski: no matching entries in passwd file
```

So I did set
```
provisioner:
  env:
    ANSIBLE_REMOTE_USER: root (user that is in Docker image)
```

and was all good from there. My Molecule config:

```yaml
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-001
    image: <my image>
    pull: true
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: private
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock

provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_USER: root
  inventory:
    group_vars:
      all:
        <inventory>
verifier:
  name: ansible

scenario:
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - destroy
```
