### ISSUE TITLE
Remove ansible_ssh_pass from delegated driver

### ISSUE THREAD

**Issue by zollo** [ansible-community/molecule#3939]
# Issue Type

- Bug report

# Molecule and Ansible details

```
Ansible 2.11+ & Molecule 3.4.0+
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

The molecule driver defines both `ansible_password` and `ansible_ssh_pass` in the instance dict, `ansible_ssh_pass` seems to take precedence (as intended).

# Actual Behaviour

In the event where where `ansible_password` is overridden via a task, inventory, etc. the connection will still use `ansible_ssh_pass`, requiring the user to override both params.

In this example, i'm overriding the username/password in a task - but this task will fail because the connection will use `ansible_ssh_pass` defined in the driver's generated inventory.
```
- name: Perform a Task
  my.custom.module:
    state: present
  vars:
    ansible_password: P@$$w0rd123
    ansible_user: newuser
```
The workaround to this would be to define ansible_ssh_pass as well:
```
- name: Perform a Task
  my.custom.module:
    state: present
  vars:
    ansible_password: P@$$w0rd123
    ansible_user: newuser
    ansible_ssh_pass: P@$$w0rd123
```

Based on https://github.com/pytest-dev/pytest-testinfra/issues/580 - the `ansible_ssh_pass` mapping should no longer be  needed, so I believe it can be safely removed.
